sonar.projectKey=pulse-ai
sonar.projectName=PulseAI Platform
sonar.sources=backendMulti,ml-backend,simulation_studio
sonar.exclusions=\
  **/venv/**,\
  **/.venv/**,\
  **/__pycache__/**,\
  **/*.pyc,\
  **/.git/**,\
  **/datasets/**,\
  **/models/**,\
  **/data/**,\
  **/mlruns/**,\
  **/*.ipynb_checkpoints/**,\
  **/*.gguf,\
  **/*.pkl,\
  **/*.db,\
  **/migrations/**,\
  **/*.ipynb,\
  **/assets/**

sonar.filesize.limit=1
sonar.python.version=3.11