# Generated by Django 6.0.3 on 2026-04-08 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_create_tables'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dashboardpersonnel',
            new_name='workspace_d_id_util_f64222_idx',
            old_name='dashboard_user_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardpersonnel',
            new_name='workspace_d_est_fav_43c4cd_idx',
            old_name='dashboard_favori_idx',
        ),
        migrations.AlterField(
            model_name='partagedashboard',
            name='id_dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partages', to='workspace.dashboardpersonnel'),
        ),
        migrations.AlterField(
            model_name='widgetslayout',
            name='id_dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets_layout', to='workspace.dashboardpersonnel'),
        ),
    ]
