# Generated by Django 6.0.3 on 2026-04-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_rename_dashboard_user_idx_workspace_d_id_util_f64222_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardpersonnel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='partagedashboard',
            options={},
        ),
        migrations.AlterModelOptions(
            name='widgetslayout',
            options={},
        ),
        migrations.AddField(
            model_name='widgetslayout',
            name='config',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='dashboardpersonnel',
            name='config',
            field=models.JSONField(default=dict),
        ),
    ]
