# Generated by Django 5.2.12 on 2026-03-27 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alertevent',
            new_name='alert_event_event_k_3b98a6_idx',
            old_name='alert_event_key_status_idx',
        ),
        migrations.RenameIndex(
            model_name='alertevent',
            new_name='alert_event_severit_393d31_idx',
            old_name='alert_event_severity_status_opened_idx',
        ),
    ]
