# Generated by Django 5.2.11 on 2026-04-03 11:22

from django.db import migrations, models


def migrate_legacy_severities(apps, schema_editor):
    AlertEvent = apps.get_model("alerts", "AlertEvent")
    AlertRule = apps.get_model("alerts", "AlertRule")
    legacy_values = ["pre_alert", "confirmed"]
    AlertEvent.objects.filter(severity__in=legacy_values).update(severity="warning")
    AlertRule.objects.filter(severity_base__in=legacy_values).update(severity_base="warning")


def reverse_migrate_legacy_severities(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_rename_alert_event_key_status_idx_alert_event_event_k_3b98a6_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_severities, reverse_migrate_legacy_severities),
        migrations.AlterField(
            model_name='alertevent',
            name='severity',
            field=models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical'), ('resolved', 'Resolved')], db_index=True, default='warning', max_length=32),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='severity_base',
            field=models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical'), ('resolved', 'Resolved')], default='warning', max_length=32),
        ),
    ]
