# Generated by Django 6.0.1 on 2026-03-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('last_updated', models.DateTimeField()),
                ('version_hash', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'data_version',
            },
        ),
    ]
