# Generated by Django 5.2.13 on 2026-05-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testUrl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('groupe_sanguin', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('poids', models.FloatField()),
                ('nb_dons', models.IntegerField(default=0)),
                ('dernier_don', models.DateField(blank=True, null=True)),
                ('disponible', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0.0)),
                ('image', models.URLField(max_length=500)),
            ],
            options={
                'db_table': 'donneurs',
            },
        ),
        migrations.AlterField(
            model_name='dataversion',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dataversion',
            name='version_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterModelTable(
            name='dataversion',
            table='data_versions',
        ),
    ]
