# Generated by Django 6.0.1 on 2026-02-23 23:29

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('blood_donation', 'Blood Donation')], default='info', max_length=20)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_by', models.CharField(default='admin', max_length=100)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-sent_at'],
            },
        ),
    ]
