# Generated by Codex for the operational digital twin app.

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TwinRun",
            fields=[
                ("run_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("mode", models.CharField(db_index=True, default="operational_shadow", max_length=64)),
                ("status", models.CharField(choices=[("created", "Created"), ("running", "Running"), ("paused", "Paused"), ("stopped", "Stopped"), ("failed", "Failed")], db_index=True, default="created", max_length=32)),
                ("config_version", models.CharField(db_index=True, max_length=64)),
                ("scenario_key", models.CharField(default="baseline", max_length=128)),
                ("strategy_key", models.CharField(default="baseline", max_length=128)),
                ("source_mode", models.CharField(choices=[("live", "Live"), ("synthetic", "Synthetic")], db_index=True, default="live", max_length=32)),
                ("seed", models.PositiveIntegerField(default=100)),
                ("created_by", models.CharField(blank=True, default="system", max_length=255)),
                ("started_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "digital_twin_run", "ordering": ["-started_at"]},
        ),
        migrations.CreateModel(
            name="TwinSnapshot",
            fields=[
                ("snapshot_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source", models.CharField(db_index=True, max_length=32)),
                ("captured_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("source_watermarks", models.JSONField(blank=True, default=dict)),
                ("normalized_payload", models.JSONField(default=dict)),
                ("redacted_payload", models.JSONField(default=dict)),
                ("freshness", models.JSONField(blank=True, default=dict)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="snapshots", to="digital_twin.twinrun")),
            ],
            options={"db_table": "digital_twin_snapshot", "ordering": ["-captured_at"]},
        ),
        migrations.CreateModel(
            name="TwinFrame",
            fields=[
                ("frame_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tick_number", models.PositiveIntegerField()),
                ("simulated_hour", models.FloatField(default=0.0)),
                ("simulated_state", models.JSONField(default=dict)),
                ("divergence", models.JSONField(blank=True, default=dict)),
                ("active_events", models.JSONField(blank=True, default=list)),
                ("active_actions", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("real_snapshot", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="frames", to="digital_twin.twinsnapshot")),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="frames", to="digital_twin.twinrun")),
            ],
            options={"db_table": "digital_twin_frame", "ordering": ["-tick_number"], "unique_together": {("run", "tick_number")}},
        ),
        migrations.CreateModel(
            name="TwinEvent",
            fields=[
                ("event_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_key", models.CharField(db_index=True, max_length=128)),
                ("source", models.CharField(db_index=True, default="manual", max_length=64)),
                ("severity", models.FloatField(default=0.5)),
                ("start_hour", models.FloatField(default=0.0)),
                ("end_hour", models.FloatField(default=0.0)),
                ("config_version", models.CharField(db_index=True, max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("applied_effects", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("active", "Active"), ("expired", "Expired"), ("cancelled", "Cancelled")], db_index=True, default="active", max_length=32)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="digital_twin.twinrun")),
            ],
            options={"db_table": "digital_twin_event", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="TwinAction",
            fields=[
                ("action_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("action_key", models.CharField(db_index=True, max_length=128)),
                ("source", models.CharField(db_index=True, default="manual", max_length=64)),
                ("requested_by", models.CharField(blank=True, default="system", max_length=255)),
                ("status", models.CharField(choices=[("simulated", "Simulated"), ("rejected", "Rejected"), ("promoted", "Promoted")], db_index=True, default="simulated", max_length=32)),
                ("simulated_effect", models.JSONField(blank=True, default=dict)),
                ("audit_metadata", models.JSONField(blank=True, default=dict)),
                ("promotion_status", models.CharField(choices=[("disabled", "Disabled"), ("not_eligible", "Not Eligible"), ("pending", "Pending"), ("promoted", "Promoted")], db_index=True, default="disabled", max_length=32)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("promoted_at", models.DateTimeField(blank=True, null=True)),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="actions", to="digital_twin.twinrun")),
            ],
            options={"db_table": "digital_twin_action", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="TwinBranch",
            fields=[
                ("branch_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("branch_key", models.CharField(db_index=True, max_length=128)),
                ("policy_overrides", models.JSONField(blank=True, default=dict)),
                ("action_overrides", models.JSONField(blank=True, default=list)),
                ("event_overrides", models.JSONField(blank=True, default=list)),
                ("summary_metrics", models.JSONField(blank=True, default=dict)),
                ("confidence_bands", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("parent_frame", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="branches", to="digital_twin.twinframe")),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="branches", to="digital_twin.twinrun")),
            ],
            options={"db_table": "digital_twin_branch", "ordering": ["-created_at"], "unique_together": {("run", "branch_key")}},
        ),
        migrations.CreateModel(
            name="TwinRecommendation",
            fields=[
                ("recommendation_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("recommendation_key", models.CharField(db_index=True, max_length=128)),
                ("rationale", models.TextField()),
                ("expected_impact", models.JSONField(blank=True, default=dict)),
                ("risk_flags", models.JSONField(blank=True, default=list)),
                ("source_tool_ids", models.JSONField(blank=True, default=list)),
                ("source_model_ids", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="recommendations", to="digital_twin.twinbranch")),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recommendations", to="digital_twin.twinrun")),
            ],
            options={"db_table": "digital_twin_recommendation", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="TwinAuditLog",
            fields=[
                ("audit_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("actor", models.CharField(blank=True, default="system", max_length=255)),
                ("action", models.CharField(db_index=True, max_length=128)),
                ("config_version", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("source_snapshot_id", models.CharField(blank=True, default="", max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="audit_logs", to="digital_twin.twinrun")),
            ],
            options={"db_table": "digital_twin_audit_log", "ordering": ["-created_at"]},
        ),
        migrations.AddIndex(model_name="twinsnapshot", index=models.Index(fields=["run", "-captured_at"], name="digital_twi_run_id_40cf4a_idx")),
        migrations.AddIndex(model_name="twinsnapshot", index=models.Index(fields=["source", "-captured_at"], name="digital_twi_source_9b282f_idx")),
        migrations.AddIndex(model_name="twinframe", index=models.Index(fields=["run", "-tick_number"], name="digital_twi_run_id_93182a_idx")),
        migrations.AddIndex(model_name="twinauditlog", index=models.Index(fields=["run", "-created_at"], name="digital_twi_run_id_eb985b_idx")),
        migrations.AddIndex(model_name="twinauditlog", index=models.Index(fields=["action", "-created_at"], name="digital_twi_action_7f3e70_idx")),
    ]
