# Generated by Django 5.2.12 on 2026-03-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeModel', models.CharField(max_length=100)),
                ('jsonResponse', models.JSONField()),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
