# Generated by Django 6.0.3 on 2026-03-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_modelresponse_filters'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='modelresponse',
            new_name='dashboard_m_region_795dbb_idx',
            old_name='dashboard_mo_region__b9cbf1_idx',
        ),
        migrations.RemoveField(
            model_name='modelresponse',
            name='extraFilters',
        ),
    ]
