# Generated by Django 5.2.12 on 2026-04-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentreDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_centre', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('fixe', 'Fixe'), ('mobile', 'Mobile'), ('hopital', 'Hôpital'), ('clinique', 'Clinique')], max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('code_postal', models.CharField(blank=True, max_length=10)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(default='France', max_length=50)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('capacite_journaliere', models.IntegerField(blank=True, null=True)),
                ('horaires', models.JSONField(blank=True, default=dict)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('ferme_temporaire', 'Fermé temporairement'), ('en_maintenance', 'En maintenance'), ('ferme_definitif', 'Fermé définitivement')], default='actif', max_length=20)),
                ('equipements', models.JSONField(blank=True, default=list)),
                ('date_ouverture', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'centre_don',
            },
        ),
    ]
