# Generated by Django 5.2.11 on 2026-03-02 23:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('file_path', models.CharField(max_length=512)),
                ('model_type', models.CharField(choices=[('sklearn', 'Scikit-learn'), ('xgboost', 'XGBoost'), ('custom', 'Custom Linear'), ('online_agent', 'Online Agent'), ('pytorch', 'PyTorch')], default='sklearn', max_length=64)),
                ('features', models.JSONField(default=list)),
                ('feature_info', models.JSONField(blank=True, default=dict)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('defaults', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ML Model',
                'verbose_name_plural': 'ML Models',
                'db_table': 'ml_model_config',
                'ordering': ['model_id'],
            },
        ),
        migrations.CreateModel(
            name='OrchestratorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('repo_id', models.CharField(default='bartowski/xLAM-7b-fc-r-GGUF', max_length=256)),
                ('filename', models.CharField(max_length=256)),
                ('size_mb', models.FloatField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('min_ram_gb', models.FloatField(default=0.0)),
                ('min_vram_mb', models.IntegerField(default=0)),
                ('n_ctx', models.IntegerField(default=4096)),
                ('n_batch', models.IntegerField(default=128)),
                ('is_selected', models.BooleanField(db_index=True, default=False)),
                ('metadata_extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Orchestrator Model',
                'verbose_name_plural': 'Orchestrator Models',
                'db_table': 'ml_orchestrator_variant',
                'ordering': ['-size_mb'],
            },
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id_used', models.CharField(blank=True, db_index=True, max_length=128)),
                ('query', models.TextField(blank=True)),
                ('features_input', models.JSONField(default=dict)),
                ('prediction_output', models.JSONField(default=dict)),
                ('planner_mode', models.CharField(blank=True, max_length=32)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('response_time_ms', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ml.mlmodelconfig')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prediction Log',
                'verbose_name_plural': 'Prediction Logs',
                'db_table': 'ml_prediction_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'success'], name='ml_predicti_created_c9b4d8_idx'), models.Index(fields=['model_id_used', '-created_at'], name='ml_predicti_model_i_097c0f_idx')],
            },
        ),
    ]
