# Generated by Django 5.2.12 on 2026-03-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodelconfig',
            name='model_type',
            field=models.CharField(choices=[('sklearn', 'Scikit-learn'), ('xgboost', 'XGBoost'), ('custom', 'Custom Linear'), ('online_agent', 'Online Agent'), ('pytorch', 'PyTorch'), ('mlflow', 'MLflow Registry')], default='sklearn', max_length=64),
        ),
    ]
