# Generated by Django 6.0.3 on 2026-03-23 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('Identifier', models.CharField(db_index=True, max_length=128, unique=True)),
                ('stats', models.JSONField(default=dict)),
                ('made_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'models_stats',
                'ordering': ['-made_at'],
            },
        ),
    ]
