# Generated by Django 6.0.3 on 2026-03-23 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_modelstats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelstats',
            old_name='Identifier',
            new_name='identifier',
        ),
    ]
