# Generated by Django 6.0.3 on 2026-03-26 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_alter_mlmodelconfig_model_type'),
        ('ml', '0003_rename_identifier_modelstats_identifier'),
    ]

    operations = []
