# Generated by Django 6.0.3 on 2026-04-05 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0004_merge_0002_alter_mlmodelconfig_model_type_0003_rename_identifier_modelstats_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriftReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(db_index=True, max_length=128)),
                ('mlflow_run_id', models.CharField(blank=True, default='', max_length=64)),
                ('drift_detected', models.BooleanField(db_index=True, default=False)),
                ('drift_score', models.FloatField(default=0.0, help_text='Fraction of features drifted (0.0–1.0)')),
                ('severity', models.CharField(choices=[('none', 'No Drift'), ('warning', 'Warning'), ('critical', 'Critical')], default='none', max_length=16)),
                ('features_checked', models.IntegerField(default=0)),
                ('features_drifted', models.IntegerField(default=0)),
                ('feature_details', models.JSONField(blank=True, default=dict, help_text='Full drift report per feature')),
                ('reference_size', models.IntegerField(default=0)),
                ('current_size', models.IntegerField(default=0)),
                ('check_type', models.CharField(default='scheduled', help_text='scheduled, manual, or post_training', max_length=32)),
                ('checked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Drift Report',
                'verbose_name_plural': 'Drift Reports',
                'db_table': 'ml_drift_report',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['model_id', '-checked_at'], name='ml_drift_re_model_i_6429b6_idx'), models.Index(fields=['-checked_at', 'drift_detected'], name='ml_drift_re_checked_11a613_idx')],
            },
        ),
    ]
