"""
dreamerv4_agent.py — Native PyTorch DreamerV4 agent for the blood supply
chain simulation.

Implements the DreamerV4 world-model-based reinforcement learning agent
(Hafner et al., "Mastering Diverse Domains through World Models" with V4
improvements) entirely in PyTorch.  The agent learns a latent world model
(RSSM), then trains an actor–critic pair purely inside imagined
trajectories generated by that model.

Exported symbols
----------------
- ``DreamerV4PolicyAgent``              — inference wrapper (drop-in for the
  JAX-based DreamerV3 agent used elsewhere in the simulator)
- ``load_dreamerv4_pytorch_agent``      — reconstruct agent from checkpoint
- ``train_dreamerv4_native``            — main training entry-point

The policy interface matches the existing ``trained_official_dreamerv3_
controller`` contract so the agent can be swapped in without changes to
``engine.py``.
"""

from __future__ import annotations

import argparse
import json
import os
import platform
import shutil
import time
from pathlib import Path
from typing import Any, Dict, List, Tuple, TypeVar

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from ppo_shared import (
    CONTINUOUS_ACTION_HIGH,
    CONTINUOUS_ACTION_LOW,
    DREAMER_ACTION_DIM,
    OBS_DIM,
)
from torch.distributions import Normal

SIMULATOR_DIR = Path(__file__).resolve().parent
DEFAULT_DREAMERV4_CHECKPOINT_NAME = "dreamerv4_agent.pt"
DREAMERV4_CHECKPOINT_CANDIDATE_NAMES = (
    DEFAULT_DREAMERV4_CHECKPOINT_NAME,
    "model.pt",
)

# ---------------------------------------------------------------------------
# MPS / Metal GPU runtime configuration
# ---------------------------------------------------------------------------

# Environment variable tunables for MPS backend performance.  These mirror
# the kind of knobs the JAX Metal backend exposes in the DreamerV3 runner
# (ENABLE_PJRT_COMPATIBILITY, XLA_PYTHON_CLIENT_PREALLOCATE, etc.).
MPS_HIGH_WATERMARK_RATIO = "0.0"  # Let PyTorch manage MPS memory dynamically
MPS_LOW_WATERMARK_RATIO = "0.0"

# ---------------------------------------------------------------------------
# Device helpers
# ---------------------------------------------------------------------------


def _is_apple_silicon() -> bool:
    """True when running on an Apple Silicon Mac."""
    return platform.system() == "Darwin" and platform.machine().lower() in {
        "arm64",
        "aarch64",
    }


def _mps_is_available() -> bool:
    """Check MPS availability without triggering heavy initialisation."""
    try:
        return (
            hasattr(torch.backends, "mps")
            and torch.backends.mps.is_available()
            and torch.backends.mps.is_built()
        )
    except Exception:
        return False


def _configure_mps_runtime() -> None:
    """Apply MPS-specific environment and runtime knobs.

    This is the PyTorch equivalent of ``configure_process_env`` in the
    DreamerV3 JAX runner — it tunes memory allocation, enables operation
    fallback, and warms the MPS shader cache so the first forward pass
    is not disproportionately slow.
    """
    # Dynamic memory management — avoids the MPS allocator reserving the
    # entire GPU VRAM up-front which can cause OOM on shared-memory Macs.
    os.environ.setdefault("PYTORCH_MPS_HIGH_WATERMARK_RATIO", MPS_HIGH_WATERMARK_RATIO)
    os.environ.setdefault("PYTORCH_MPS_LOW_WATERMARK_RATIO", MPS_LOW_WATERMARK_RATIO)
    # Allow ops without a Metal kernel to fall back to CPU transparently.
    os.environ.setdefault("PYTORCH_ENABLE_MPS_FALLBACK", "1")


def _configure_cuda_runtime() -> None:
    """Apply safe CUDA performance defaults for notebook and CLI training."""
    if not torch.cuda.is_available():
        return
    if hasattr(torch, "set_float32_matmul_precision"):
        torch.set_float32_matmul_precision("high")
    if hasattr(torch.backends, "cuda") and hasattr(torch.backends.cuda, "matmul"):
        torch.backends.cuda.matmul.allow_tf32 = True
    if hasattr(torch.backends, "cudnn"):
        torch.backends.cudnn.allow_tf32 = True
        torch.backends.cudnn.benchmark = True


def _auto_detect_device() -> torch.device:
    """Pick the best available accelerator: CUDA → MPS (Apple Silicon) → CPU.

    When MPS is selected the function also calls ``_configure_mps_runtime``
    so that all Metal-specific knobs are set before the first kernel launch.
    """
    if torch.cuda.is_available():
        _configure_cuda_runtime()
        return torch.device("cuda")
    if _mps_is_available():
        _configure_mps_runtime()
        return torch.device("mps")
    return torch.device("cpu")


def _resolve_device(name: str | None) -> torch.device:
    """Resolve a user-supplied device string (or *None* for auto-detect)."""
    if name is None or name == "auto":
        return _auto_detect_device()
    device = torch.device(name)
    if device.type == "mps":
        _configure_mps_runtime()
    elif device.type == "cuda":
        _configure_cuda_runtime()
    return device


def _resolve_cuda_device_ids(
    device: torch.device,
    *,
    max_devices: int = 0,
) -> list[int]:
    """Return the visible CUDA device ids that should participate in training."""
    if device.type != "cuda" or not torch.cuda.is_available():
        return []

    if device.index is not None:
        return [int(device.index)]

    count = int(torch.cuda.device_count())
    if max_devices > 0:
        count = min(count, int(max_devices))
    return list(range(count))


def _data_parallel_enabled(
    device: torch.device,
    *,
    requested: bool,
    batch_size: int,
    device_ids: list[int],
) -> bool:
    if not requested or device.type != "cuda":
        return False
    if len(device_ids) < 2:
        return False
    return int(batch_size) >= len(device_ids)


def _configure_runtime_env(*, online_city_graph: bool = False) -> None:
    """Align native training defaults with the official Dreamer runtime."""
    if not online_city_graph:
        os.environ.setdefault("PIOS_SIM_OFFLINE", "1")


def _resolve_native_env_count(
    requested_envs: int,
    *,
    device: torch.device | None = None,
    cuda_device_ids: list[int] | None = None,
) -> int:
    """Choose a practical default number of collection envs."""
    if requested_envs > 0:
        return requested_envs
    workers = max(1, int(os.cpu_count() or 1))
    if device is not None and device.type == "cuda":
        gpu_count = max(1, len(cuda_device_ids or []) or int(torch.cuda.device_count()))
        return min(8, max(2 * gpu_count, workers // 2))
    return min(4, max(1, workers // 2))


_M = TypeVar("_M", bound=nn.Module)


def _maybe_compile(
    module: _M,
    device: torch.device,
    *,
    disable: bool = False,
) -> _M:
    """Wrap *module* with ``torch.compile`` when the backend supports it.

    On MPS (Apple Metal) we use the ``aot_eager`` backend which fuses
    Python overhead and enables operator fusion without requiring a full
    Inductor/Triton stack.  On CUDA the default ``inductor`` backend is
    used.  Compilation is skipped on CPU or when *disable* is True.

    This is the PyTorch analogue of the JAX XLA compilation cache that
    the DreamerV3 Metal runner enables via ``XDG_CACHE_HOME``.
    """
    if disable:
        return module
    if not hasattr(torch, "compile"):
        return module  # PyTorch < 2.0
    try:
        if device.type == "mps":
            return torch.compile(module, backend="aot_eager")  # type: ignore[return-value]
        if device.type == "cuda":
            return torch.compile(module, mode="reduce-overhead")  # type: ignore[return-value]
    except Exception:
        # Graceful degradation — compilation is best-effort.
        pass
    return module


NATIVE_MODEL_PRESETS: Dict[str, Dict[str, int]] = {
    "default": {
        "hidden_size": 256,
        "stoch_categories": 16,
        "stoch_classes": 16,
        "mlp_units": 256,
    },
    "fast": {
        "hidden_size": 128,
        "stoch_categories": 8,
        "stoch_classes": 8,
        "mlp_units": 128,
    },
}


def _resolve_native_model_config(
    *,
    obs_dim: int,
    action_dim: int,
    preset: str = "default",
    hidden_size: int | None = None,
    stoch_categories: int | None = None,
    stoch_classes: int | None = None,
    mlp_units: int | None = None,
) -> Dict[str, int]:
    if preset not in NATIVE_MODEL_PRESETS:
        raise ValueError(
            f"Unknown native model preset {preset!r}. "
            f"Expected one of {sorted(NATIVE_MODEL_PRESETS)}."
        )

    config = dict(NATIVE_MODEL_PRESETS[preset])
    overrides = {
        "hidden_size": hidden_size,
        "stoch_categories": stoch_categories,
        "stoch_classes": stoch_classes,
        "mlp_units": mlp_units,
    }
    for key, value in overrides.items():
        if value is not None:
            if int(value) < 1:
                raise ValueError(f"{key} must be >= 1, got {value!r}.")
            config[key] = int(value)

    return {
        "obs_dim": int(obs_dim),
        "action_dim": int(action_dim),
        **config,
    }


# ---------------------------------------------------------------------------
# Utility helpers
# ---------------------------------------------------------------------------


def symlog(x: torch.Tensor) -> torch.Tensor:
    """Symmetric logarithmic compression."""
    return torch.sign(x) * torch.log1p(torch.abs(x))


def symexp(x: torch.Tensor) -> torch.Tensor:
    """Inverse of symlog."""
    return torch.sign(x) * (torch.exp(torch.abs(x)) - 1.0)


def _straight_through_one_hot(logits: torch.Tensor, n_classes: int) -> torch.Tensor:
    """Sample one-hot from logits with straight-through gradients.

    Parameters
    ----------
    logits : (*, n_categories, n_classes)
    n_classes : int

    Returns
    -------
    one_hot : same shape as *logits*, hard one-hot forward, soft backward
    """
    probs = F.softmax(logits, dim=-1)
    indices = torch.argmax(
        probs + torch.rand_like(probs) * 1e-6,  # break ties
        dim=-1,
    )
    hard = F.one_hot(indices, n_classes).float()
    # Straight-through: forward uses hard, backward uses probs
    return hard + probs - probs.detach()


# ---------------------------------------------------------------------------
# RSSM World Model
# ---------------------------------------------------------------------------


class RSSM(nn.Module):
    """Recurrent State-Space Model with categorical stochastic latents."""

    def __init__(
        self,
        obs_dim: int = OBS_DIM,
        action_dim: int = DREAMER_ACTION_DIM,
        hidden_size: int = 256,
        stoch_categories: int = 16,
        stoch_classes: int = 16,
        mlp_units: int = 256,
    ):
        super().__init__()
        self.obs_dim = obs_dim
        self.action_dim = action_dim
        self.hidden_size = hidden_size
        self.stoch_categories = stoch_categories
        self.stoch_classes = stoch_classes
        self.stoch_dim = stoch_categories * stoch_classes  # 256
        self.state_feat_dim = hidden_size + self.stoch_dim  # 512
        self.mlp_units = mlp_units

        # --- Encoder ---
        self.encoder = nn.Sequential(
            nn.Linear(obs_dim, mlp_units),
            nn.LayerNorm(mlp_units),
            nn.SiLU(),
            nn.Linear(mlp_units, mlp_units),
            nn.LayerNorm(mlp_units),
            nn.SiLU(),
            nn.Linear(mlp_units, mlp_units),
        )

        # --- Sequence model (GRU) ---
        self.gru_input = nn.Linear(self.stoch_dim + action_dim, hidden_size)
        self.gru_cell = nn.GRUCell(hidden_size, hidden_size)

        # --- Posterior  q(z | h, embed) ---
        self.posterior_net = nn.Sequential(
            nn.Linear(hidden_size + mlp_units, mlp_units),
            nn.LayerNorm(mlp_units),
            nn.SiLU(),
            nn.Linear(mlp_units, self.stoch_dim),
        )

        # --- Prior  p(z | h) ---
        self.prior_net = nn.Sequential(
            nn.Linear(hidden_size, mlp_units),
            nn.LayerNorm(mlp_units),
            nn.SiLU(),
            nn.Linear(mlp_units, self.stoch_dim),
        )

        # --- Observation decoder ---
        self.obs_decoder = nn.Sequential(
            nn.Linear(self.state_feat_dim, mlp_units),
            nn.LayerNorm(mlp_units),
            nn.SiLU(),
            nn.Linear(mlp_units, mlp_units),
            nn.LayerNorm(mlp_units),
            nn.SiLU(),
            nn.Linear(mlp_units, obs_dim),
        )

        # --- Reward predictor ---
        self.reward_head = nn.Sequential(
            nn.Linear(self.state_feat_dim, mlp_units),
            nn.LayerNorm(mlp_units),
            nn.SiLU(),
            nn.Linear(mlp_units, 128),
            nn.LayerNorm(128),
            nn.SiLU(),
            nn.Linear(128, 1),
        )

        # --- Continue predictor ---
        self.continue_head = nn.Sequential(
            nn.Linear(self.state_feat_dim, mlp_units),
            nn.LayerNorm(mlp_units),
            nn.SiLU(),
            nn.Linear(mlp_units, 128),
            nn.LayerNorm(128),
            nn.SiLU(),
            nn.Linear(128, 1),
        )

    # ----- helpers -----

    def initial_state(
        self, batch_size: int, device: torch.device | None = None
    ) -> Dict[str, torch.Tensor]:
        """Return a zero-initialised recurrent state dict."""
        dev = device or next(self.parameters()).device
        return {
            "h": torch.zeros(batch_size, self.hidden_size, device=dev),
            "z": torch.zeros(batch_size, self.stoch_dim, device=dev),
        }

    def state_features(self, state: Dict[str, torch.Tensor]) -> torch.Tensor:
        """Concatenate deterministic and stochastic state → (B, 512)."""
        return torch.cat([state["h"], state["z"]], dim=-1)

    def _reshape_stoch_logits(self, raw: torch.Tensor) -> torch.Tensor:
        """(B, stoch_dim) → (B, n_categories, n_classes)."""
        return raw.view(-1, self.stoch_categories, self.stoch_classes)

    def _sample_stoch(self, logits: torch.Tensor) -> torch.Tensor:
        """Sample stoch state from (B, n_cat, n_cls) logits → (B, stoch_dim)."""
        z = _straight_through_one_hot(logits, self.stoch_classes)
        return z.view(-1, self.stoch_dim)

    # ----- sequence step -----

    def sequence_step(
        self,
        prev_state: Dict[str, torch.Tensor],
        prev_action: torch.Tensor,
    ) -> torch.Tensor:
        """Advance deterministic state h given previous z and action."""
        x = torch.cat([prev_state["z"], prev_action], dim=-1)
        x = self.gru_input(x)
        x = F.silu(x)
        h = self.gru_cell(x, prev_state["h"])
        return h

    def posterior(
        self, h: torch.Tensor, embed: torch.Tensor
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        """Posterior logits and sampled z given h and observation embedding."""
        x = torch.cat([h, embed], dim=-1)
        logits = self._reshape_stoch_logits(self.posterior_net(x))
        z = self._sample_stoch(logits)
        return logits, z

    def prior(self, h: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        """Prior logits and sampled z from h alone."""
        logits = self._reshape_stoch_logits(self.prior_net(h))
        z = self._sample_stoch(logits)
        return logits, z

    def encode(self, obs: torch.Tensor) -> torch.Tensor:
        """Encode observation vector → embedding."""
        return self.encoder(obs)

    def decode_obs(self, feat: torch.Tensor) -> torch.Tensor:
        """Predict symlog(obs) from state features."""
        return self.obs_decoder(feat)

    def decode_reward(self, feat: torch.Tensor) -> torch.Tensor:
        """Predict symlog(reward) from state features."""
        return self.reward_head(feat)

    def decode_continue(self, feat: torch.Tensor) -> torch.Tensor:
        """Predict continue logit from state features."""
        return self.continue_head(feat)

    # ----- full forward (observe sequence) -----

    def observe(
        self,
        obs_seq: torch.Tensor,
        action_seq: torch.Tensor,
        is_first_seq: torch.Tensor,
        prev_state: Dict[str, torch.Tensor] | None = None,
    ) -> Dict[str, Any]:
        """Process a sequence of observations and actions.

        Parameters
        ----------
        obs_seq      : (B, T, obs_dim)
        action_seq   : (B, T, action_dim)
        is_first_seq : (B, T)
        prev_state   : optional initial state dict

        Returns
        -------
        Dict with keys: h_seq, post_logits, prior_logits, post_z_seq,
                        feat_seq, final_state  — all (B, T, ...).

        MPS optimisation
        ----------------
        The inner loop is the primary training bottleneck on Apple Metal
        because each GRU timestep launches many small MPS kernels.  This
        version minimises per-step overhead by:

        * Pre-allocating output tensors and writing via sliced assignment
          instead of appending to Python lists and ``torch.stack``-ing
          (avoids T intermediate allocations + 1 stack copy).
        * Fusing the first-step mask multiply into a single in-place op
          instead of two separate multiplies on h and z.
        * Computing the encoder embedding once for the whole sequence
          before entering the loop (already done, kept for clarity).
        """
        B, T, _ = obs_seq.shape
        device = obs_seq.device

        if prev_state is None:
            prev_state = self.initial_state(B, device)

        # Encode all observations in one batched forward pass.
        embed_seq = self.encode(obs_seq.reshape(B * T, -1)).view(B, T, -1)

        # Pre-allocate output tensors to avoid per-step list appends and
        # the final torch.stack copy — a significant MPS allocation saving.
        h_seq = torch.empty(B, T, self.hidden_size, device=device)
        post_logits_seq = torch.empty(
            B, T, self.stoch_categories, self.stoch_classes, device=device
        )
        prior_logits_seq = torch.empty(
            B, T, self.stoch_categories, self.stoch_classes, device=device
        )
        post_z_seq = torch.empty(B, T, self.stoch_dim, device=device)

        h = prev_state["h"]
        z = prev_state["z"]

        for t in range(T):
            # Reset recurrent state for episodes that just started.
            # Fused mask: one multiply on the concatenated [h, z] is
            # cheaper than two separate masked multiplies on MPS.
            mask = is_first_seq[:, t].unsqueeze(-1)  # (B, 1)
            if mask.any():
                inv = 1.0 - mask
                h = h * inv
                z = z * inv

            # Deterministic step — inlined to avoid dict allocation
            x = torch.cat([z, action_seq[:, t]], dim=-1)
            x = F.silu(self.gru_input(x))
            h = self.gru_cell(x, h)

            # Posterior
            post_inp = torch.cat([h, embed_seq[:, t]], dim=-1)
            post_raw = self.posterior_net(post_inp)
            post_logits = post_raw.view(B, self.stoch_categories, self.stoch_classes)
            z = self._sample_stoch(post_logits)

            # Prior (for KL — detached from the posterior path)
            prior_raw = self.prior_net(h)
            prior_logits = prior_raw.view(B, self.stoch_categories, self.stoch_classes)

            # Write into pre-allocated tensors
            h_seq[:, t] = h
            post_logits_seq[:, t] = post_logits
            prior_logits_seq[:, t] = prior_logits
            post_z_seq[:, t] = z

        feat_seq = torch.cat([h_seq, post_z_seq], dim=-1)  # (B, T, state_feat_dim)

        return {
            "h_seq": h_seq,
            "post_logits": post_logits_seq,
            "prior_logits": prior_logits_seq,
            "post_z_seq": post_z_seq,
            "feat_seq": feat_seq,
            "final_state": {"h": h, "z": z},
        }


# ---------------------------------------------------------------------------
# Actor & Critic
# ---------------------------------------------------------------------------


class Actor(nn.Module):
    """TanhNormal policy network."""

    def __init__(self, state_feat_dim: int, action_dim: int, mlp_units: int = 256):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(state_feat_dim, mlp_units),
            nn.LayerNorm(mlp_units),
            nn.SiLU(),
            nn.Linear(mlp_units, mlp_units),
            nn.LayerNorm(mlp_units),
            nn.SiLU(),
        )
        self.mean_head = nn.Linear(mlp_units, action_dim)
        self.log_std_head = nn.Linear(mlp_units, action_dim)
        self.action_dim = action_dim
        self._log_std_min = -5.0
        self._log_std_max = 2.0

    def forward(
        self,
        feat: torch.Tensor,
        *,
        sample: bool = True,
    ) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        """Compute action, log-probability, and entropy.

        Returns
        -------
        action   : (*, action_dim)  in [-1, 1]
        log_prob : (*, )
        entropy  : (*, )
        """
        h = self.net(feat)
        mean = self.mean_head(h)
        log_std = self.log_std_head(h).clamp(self._log_std_min, self._log_std_max)
        std = log_std.exp()

        dist = Normal(mean, std)
        if sample:
            x = dist.rsample()
        else:
            x = mean

        # Tanh squash
        action = torch.tanh(x)

        # Log-prob with tanh correction
        log_prob = dist.log_prob(x) - torch.log(1.0 - action.pow(2) + 1e-6)
        log_prob = log_prob.sum(dim=-1)

        # Entropy (approximate via Normal entropy; tanh correction is small)
        entropy = dist.entropy().sum(dim=-1)

        return action, log_prob, entropy

    def act_eval(self, feat: torch.Tensor) -> torch.Tensor:
        """Deterministic action for evaluation (tanh of the mean)."""
        h = self.net(feat)
        mean = self.mean_head(h)
        return torch.tanh(mean)


class Critic(nn.Module):
    """State-value critic predicting symlog(value)."""

    def __init__(self, state_feat_dim: int, mlp_units: int = 256):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(state_feat_dim, mlp_units),
            nn.LayerNorm(mlp_units),
            nn.SiLU(),
            nn.Linear(mlp_units, mlp_units),
            nn.LayerNorm(mlp_units),
            nn.SiLU(),
            nn.Linear(mlp_units, 1),
        )

    def forward(self, feat: torch.Tensor) -> torch.Tensor:
        """Return symlog-encoded value prediction (*, 1)."""
        return self.net(feat)


# ---------------------------------------------------------------------------
# Replay Buffer
# ---------------------------------------------------------------------------


class ReplayBuffer:
    """Contiguous replay storage with O(1) append and vectorized sampling."""

    def __init__(self, capacity: int = 500_000):
        self.capacity = capacity
        self._obs: np.ndarray | None = None
        self._action: np.ndarray | None = None
        self._reward: np.ndarray | None = None
        self._is_first: np.ndarray | None = None
        self._done: np.ndarray | None = None
        self._size = 0
        self._next_idx = 0

    @property
    def size(self) -> int:
        return self._size

    def _ensure_storage(self, obs: np.ndarray, action: np.ndarray) -> None:
        if self._obs is not None:
            return
        self._obs = np.empty((self.capacity, obs.size), dtype=np.float32)
        self._action = np.empty((self.capacity, action.size), dtype=np.float32)
        self._reward = np.empty((self.capacity,), dtype=np.float32)
        self._is_first = np.empty((self.capacity,), dtype=np.bool_)
        self._done = np.empty((self.capacity,), dtype=np.bool_)

    def _logical_to_physical(self, logical_idx: np.ndarray) -> np.ndarray:
        start = self._next_idx - self._size
        return (start + logical_idx) % self.capacity

    def add(
        self,
        obs: np.ndarray,
        action: np.ndarray,
        reward: float,
        is_first: bool,
        done: bool,
    ) -> None:
        """Add a single transition."""
        obs_arr = np.asarray(obs, dtype=np.float32).ravel()
        action_arr = np.asarray(action, dtype=np.float32).ravel()
        self._ensure_storage(obs_arr, action_arr)

        idx = self._next_idx
        assert self._obs is not None
        assert self._action is not None
        assert self._reward is not None
        assert self._is_first is not None
        assert self._done is not None

        self._obs[idx] = obs_arr
        self._action[idx] = action_arr
        self._reward[idx] = np.float32(reward)
        self._is_first[idx] = np.bool_(is_first)
        self._done[idx] = np.bool_(done)

        self._next_idx = (idx + 1) % self.capacity
        self._size = min(self._size + 1, self.capacity)

    def sample(
        self,
        batch_size: int,
        seq_len: int,
    ) -> Dict[str, np.ndarray]:
        """Sample uniform random subsequences.

        Returns dict with arrays of shape (batch_size, seq_len, ...).
        """
        max_start = self._size - seq_len
        if max_start < 1:
            raise RuntimeError(
                f"Buffer has {self._size} transitions but needs at least {seq_len + 1}."
            )

        starts = np.random.randint(0, max_start, size=batch_size)
        logical_idx = starts[:, None] + np.arange(seq_len)[None, :]
        physical_idx = self._logical_to_physical(logical_idx)

        assert self._obs is not None
        assert self._action is not None
        assert self._reward is not None
        assert self._is_first is not None
        assert self._done is not None

        return {
            "obs": self._obs[physical_idx],  # (B, T, obs_dim)
            "action": self._action[physical_idx],  # (B, T, act_dim)
            "reward": self._reward[physical_idx],  # (B, T)
            "is_first": self._is_first[physical_idx],  # (B, T)
            "done": self._done[physical_idx],  # (B, T)
        }


class MultiEnvReplayBuffer:
    """Independent per-env replay buffers with mixed-batch sampling."""

    def __init__(self, num_envs: int, capacity: int = 500_000):
        self.num_envs = max(1, int(num_envs))
        per_env_capacity = max(1, (int(capacity) + self.num_envs - 1) // self.num_envs)
        self._buffers = [ReplayBuffer(per_env_capacity) for _ in range(self.num_envs)]

    @property
    def size(self) -> int:
        return sum(buffer.size for buffer in self._buffers)

    def can_sample(self, seq_len: int) -> bool:
        return any(buffer.size > seq_len for buffer in self._buffers)

    def add(
        self,
        env_idx: int,
        obs: np.ndarray,
        action: np.ndarray,
        reward: float,
        is_first: bool,
        done: bool,
    ) -> None:
        self._buffers[int(env_idx)].add(obs, action, reward, is_first, done)

    def sample(
        self,
        batch_size: int,
        seq_len: int,
    ) -> Dict[str, np.ndarray]:
        eligible = [buffer for buffer in self._buffers if buffer.size > seq_len]
        if not eligible:
            raise RuntimeError(
                f"No replay buffer has enough transitions for seq_len={seq_len}."
            )

        selected = np.random.randint(0, len(eligible), size=batch_size)
        unique, counts = np.unique(selected, return_counts=True)
        parts = [
            eligible[int(idx)].sample(int(count), seq_len)
            for idx, count in zip(unique, counts)
        ]

        if len(parts) == 1:
            return parts[0]

        merged = {
            key: np.concatenate([part[key] for part in parts], axis=0)
            for key in parts[0]
        }
        order = np.random.permutation(batch_size)
        return {key: value[order] for key, value in merged.items()}


# ---------------------------------------------------------------------------
# Return Normalization (exponential moving percentiles)
# ---------------------------------------------------------------------------


class ReturnNormalizer:
    """Normalise returns using exponential moving 5th / 95th percentiles."""

    def __init__(
        self,
        decay: float = 0.99,
        percentile_low: float = 5.0,
        percentile_high: float = 95.0,
    ):
        self.decay = decay
        self.percentile_low = percentile_low
        self.percentile_high = percentile_high
        self._low = 0.0
        self._high = 1.0
        self._initialised = False

    def update(self, returns: torch.Tensor) -> None:
        flat = returns.detach().cpu().numpy().ravel()
        if flat.size == 0:
            return
        lo = float(np.percentile(flat, self.percentile_low))
        hi = float(np.percentile(flat, self.percentile_high))
        if not self._initialised:
            self._low = lo
            self._high = hi
            self._initialised = True
        else:
            self._low = self.decay * self._low + (1.0 - self.decay) * lo
            self._high = self.decay * self._high + (1.0 - self.decay) * hi

    def normalize(self, returns: torch.Tensor) -> torch.Tensor:
        span = max(self._high - self._low, 1e-8)
        return (returns - self._low) / span


# ---------------------------------------------------------------------------
# KL divergence helpers
# ---------------------------------------------------------------------------


def _categorical_kl(
    post_logits: torch.Tensor,
    prior_logits: torch.Tensor,
    free_nats: float = 1.0,
    balance: float = 0.8,
) -> Tuple[torch.Tensor, Dict[str, float]]:
    """Compute KL-balanced categorical KL with free bits.

    Parameters
    ----------
    post_logits, prior_logits : (B, T, n_cat, n_cls)
    free_nats : minimum KL per category
    balance   : fraction for dynamics loss (1 - balance for representation)

    Returns
    -------
    loss : scalar
    info : dict of logged scalars
    """
    post_probs = F.softmax(post_logits, dim=-1)
    _prior_probs = F.softmax(prior_logits, dim=-1)  # noqa: F841 — used only via log_softmax

    # KL per category: sum_c p(c) log(p(c)/q(c))
    kl_per_cat = (
        post_probs
        * (F.log_softmax(post_logits, dim=-1) - F.log_softmax(prior_logits, dim=-1))
    ).sum(dim=-1)  # (B, T, n_cat)

    # Free bits: clamp per category
    kl_free = torch.clamp(kl_per_cat, min=free_nats / post_logits.shape[-2])

    # Sum over categories → (B, T)
    kl_value = kl_free.sum(dim=-1)

    # KL balancing
    # dynamics loss: update prior towards posterior (stop-grad posterior)
    dyn_kl = (
        (
            F.softmax(post_logits.detach(), dim=-1)
            * (
                F.log_softmax(post_logits.detach(), dim=-1)
                - F.log_softmax(prior_logits, dim=-1)
            )
        )
        .sum(dim=-1)
        .sum(dim=-1)
    )  # (B, T)
    dyn_kl = torch.clamp(dyn_kl, min=0.0)

    # representation loss: update posterior towards prior (stop-grad prior)
    rep_kl = (
        (
            F.softmax(post_logits, dim=-1)
            * (
                F.log_softmax(post_logits, dim=-1)
                - F.log_softmax(prior_logits.detach(), dim=-1)
            )
        )
        .sum(dim=-1)
        .sum(dim=-1)
    )  # (B, T)
    rep_kl = torch.clamp(rep_kl, min=0.0)

    loss = balance * dyn_kl.mean() + (1.0 - balance) * rep_kl.mean()

    info = {
        "kl_value": float(kl_value.mean().item()),
        "kl_dyn": float(dyn_kl.mean().item()),
        "kl_rep": float(rep_kl.mean().item()),
    }
    return loss, info


def _batch_to_device_tensors(
    batch: Dict[str, np.ndarray],
    device: torch.device,
    *,
    non_blocking: bool = False,
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
    obs = torch.from_numpy(batch["obs"]).to(device, non_blocking=non_blocking)
    actions = torch.from_numpy(batch["action"]).to(device, non_blocking=non_blocking)
    rewards = torch.from_numpy(batch["reward"]).to(device, non_blocking=non_blocking)
    is_first = torch.from_numpy(batch["is_first"].astype("float32")).to(
        device, non_blocking=non_blocking
    )
    dones = torch.from_numpy(batch["done"].astype("float32")).to(
        device, non_blocking=non_blocking
    )
    return obs, actions, rewards, is_first, dones


class _WorldModelLossModule(nn.Module):
    """Compute world-model losses in a form that can be data-parallelised."""

    def __init__(self, rssm: RSSM):
        super().__init__()
        self.rssm = rssm

    def forward(
        self,
        obs: torch.Tensor,
        actions: torch.Tensor,
        rewards: torch.Tensor,
        is_first: torch.Tensor,
        dones: torch.Tensor,
        free_nats: float,
        kl_balance: float,
        kl_scale: float,
    ) -> Dict[str, torch.Tensor]:
        B, T, _ = obs.shape
        prev_actions = torch.cat(
            [torch.zeros(B, 1, actions.shape[-1], device=obs.device), actions[:, :-1]],
            dim=1,
        )

        out = self.rssm.observe(obs, prev_actions, is_first)
        feat = out["feat_seq"]

        obs_pred = self.rssm.decode_obs(feat)
        obs_target = symlog(obs)
        obs_loss = F.mse_loss(obs_pred, obs_target)

        rew_pred = self.rssm.decode_reward(feat).squeeze(-1)
        rew_target = symlog(rewards)
        rew_loss = F.mse_loss(rew_pred, rew_target)

        cont_pred = self.rssm.decode_continue(feat).squeeze(-1)
        cont_target = 1.0 - dones.float()
        cont_loss = F.binary_cross_entropy_with_logits(cont_pred, cont_target)

        kl_loss, kl_info = _categorical_kl(
            out["post_logits"],
            out["prior_logits"],
            free_nats=free_nats,
            balance=kl_balance,
        )
        total_loss = obs_loss + rew_loss + cont_loss + kl_scale * kl_loss

        return {
            "total_loss": total_loss.unsqueeze(0),
            "obs_loss": obs_loss.detach().unsqueeze(0),
            "rew_loss": rew_loss.detach().unsqueeze(0),
            "cont_loss": cont_loss.detach().unsqueeze(0),
            "kl_value": torch.tensor(
                [kl_info["kl_value"]], device=obs.device, dtype=torch.float32
            ),
            "kl_dyn": torch.tensor(
                [kl_info["kl_dyn"]], device=obs.device, dtype=torch.float32
            ),
            "kl_rep": torch.tensor(
                [kl_info["kl_rep"]], device=obs.device, dtype=torch.float32
            ),
            "chunk_weight": torch.tensor([float(B)], device=obs.device),
            "final_h": out["final_state"]["h"].detach(),
            "final_z": out["final_state"]["z"].detach(),
        }


class _ActorCriticRolloutModule(nn.Module):
    """Compute actor/critic rollout tensors for optional data parallelism."""

    def __init__(
        self,
        rssm: RSSM,
        actor: Actor,
        critic: Critic,
        target_critic: Critic,
    ):
        super().__init__()
        self.rssm = rssm
        self.actor = actor
        self.critic = critic
        self.target_critic = target_critic

    def forward(
        self,
        initial_h: torch.Tensor,
        initial_z: torch.Tensor,
        horizon: int,
        gamma: float,
        lambda_: float,
    ) -> Dict[str, torch.Tensor]:
        initial_state = {"h": initial_h, "z": initial_z}
        traj = imagine_trajectory(self.rssm, self.actor, initial_state, horizon)

        feats = traj["feats"]
        feats_detached = feats.detach()
        rewards = symexp(traj["reward_preds"].detach())
        continues = traj["continue_preds"]

        with torch.no_grad():
            target_values_sym = self.target_critic(feats_detached).squeeze(-1)
            target_values = symexp(target_values_sym)
            lambda_returns = compute_lambda_returns(
                rewards, target_values, continues.detach(), gamma, lambda_
            )

        values_sym = self.critic(feats_detached).squeeze(-1)

        return {
            "log_probs": traj["log_probs"],
            "entropies": traj["entropies"],
            "lambda_returns": lambda_returns.detach(),
            "values_sym": values_sym,
            "values_for_adv": target_values.detach(),
            "chunk_weight": torch.tensor(
                [float(initial_h.shape[0])], device=initial_h.device
            ),
        }


# ---------------------------------------------------------------------------
# World-model training step
# ---------------------------------------------------------------------------


def train_world_model(
    rssm: RSSM,
    optimizer: torch.optim.Optimizer,
    batch: Dict[str, np.ndarray],
    device: torch.device,
    free_nats: float = 1.0,
    kl_balance: float = 0.8,
    kl_scale: float = 1.0,
    parallel_module: nn.Module | None = None,
    _non_blocking: bool = False,
) -> Tuple[Dict[str, float], Dict[str, torch.Tensor]]:
    """One gradient step on the world model.

    Returns
    -------
    (metrics_dict, final_state)
        *final_state* can be reused as the imagination starting point so the
        caller does not need a redundant ``rssm.observe`` call.
    """
    # Use non_blocking=True for async CPU→GPU transfer when the source
    # tensors live in pinned (page-locked) memory.  On MPS this allows the
    # CPU to continue filling the next batch while the current transfer
    # proceeds over the unified-memory fabric.
    nb = _non_blocking
    obs, actions, rewards, is_first, dones = _batch_to_device_tensors(
        batch,
        device,
        non_blocking=nb,
    )

    if parallel_module is None:
        B, T, _ = obs.shape

        # Shift actions so action[t] is the action *before* obs[t]
        prev_actions = torch.cat(
            [torch.zeros(B, 1, actions.shape[-1], device=device), actions[:, :-1]],
            dim=1,
        )

        out = rssm.observe(obs, prev_actions, is_first)
        feat = out["feat_seq"]  # (B, T, 512)

        # --- Reconstruction loss (symlog MSE) ---
        obs_pred = rssm.decode_obs(feat)  # (B, T, obs_dim)
        obs_target = symlog(obs)
        obs_loss = F.mse_loss(obs_pred, obs_target)

        # --- Reward loss (symlog MSE) ---
        rew_pred = rssm.decode_reward(feat).squeeze(-1)  # (B, T)
        rew_target = symlog(rewards)
        rew_loss = F.mse_loss(rew_pred, rew_target)

        # --- Continue loss (binary cross-entropy) ---
        cont_pred = rssm.decode_continue(feat).squeeze(-1)  # (B, T)
        cont_target = 1.0 - dones.float()
        cont_loss = F.binary_cross_entropy_with_logits(cont_pred, cont_target)

        # --- KL loss ---
        kl_loss, kl_info = _categorical_kl(
            out["post_logits"],
            out["prior_logits"],
            free_nats=free_nats,
            balance=kl_balance,
        )

        total_loss = obs_loss + rew_loss + cont_loss + kl_scale * kl_loss

        optimizer.zero_grad(set_to_none=True)
        total_loss.backward()
        nn.utils.clip_grad_norm_(rssm.parameters(), 100.0)
        optimizer.step()

        final_state = {k: v.detach() for k, v in out["final_state"].items()}

        metrics = {
            "wm/total": float(total_loss.item()),
            "wm/obs": float(obs_loss.item()),
            "wm/rew": float(rew_loss.item()),
            "wm/cont": float(cont_loss.item()),
            "wm/kl": float(kl_info["kl_value"]),
            "wm/kl_dyn": float(kl_info["kl_dyn"]),
            "wm/kl_rep": float(kl_info["kl_rep"]),
        }
        return metrics, final_state

    outputs = parallel_module(
        obs,
        actions,
        rewards,
        is_first,
        dones,
        free_nats,
        kl_balance,
        kl_scale,
    )
    weights = outputs["chunk_weight"].reshape(-1)
    total_loss = (outputs["total_loss"].reshape(-1) * weights).sum() / weights.sum()

    optimizer.zero_grad(set_to_none=True)
    total_loss.backward()
    nn.utils.clip_grad_norm_(rssm.parameters(), 100.0)
    optimizer.step()

    final_state = {
        "h": outputs["final_h"].detach(),
        "z": outputs["final_z"].detach(),
    }
    metrics = {
        "wm/total": float(total_loss.item()),
        "wm/obs": float(
            (outputs["obs_loss"].reshape(-1) * weights).sum().item() / weights.sum().item()
        ),
        "wm/rew": float(
            (outputs["rew_loss"].reshape(-1) * weights).sum().item() / weights.sum().item()
        ),
        "wm/cont": float(
            (outputs["cont_loss"].reshape(-1) * weights).sum().item() / weights.sum().item()
        ),
        "wm/kl": float(
            (outputs["kl_value"].reshape(-1) * weights).sum().item() / weights.sum().item()
        ),
        "wm/kl_dyn": float(
            (outputs["kl_dyn"].reshape(-1) * weights).sum().item() / weights.sum().item()
        ),
        "wm/kl_rep": float(
            (outputs["kl_rep"].reshape(-1) * weights).sum().item() / weights.sum().item()
        ),
    }
    return metrics, final_state


# ---------------------------------------------------------------------------
# Imagination rollout & actor-critic training
# ---------------------------------------------------------------------------


def imagine_trajectory(
    rssm: RSSM,
    actor: Actor,
    initial_state: Dict[str, torch.Tensor],
    horizon: int,
) -> Dict[str, torch.Tensor]:
    """Roll out the actor in the learned world model.

    Parameters
    ----------
    initial_state : dict with "h" (B, H) and "z" (B, stoch_dim)
    horizon : number of imagined steps

    Returns
    -------
    Dict with feats, actions, log_probs, entropies, reward_preds,
    continue_preds — all (B, horizon, ...).

    """
    feats = []
    actions = []
    log_probs = []
    entropies = []
    reward_preds = []
    continue_preds = []

    state = {k: v.detach() for k, v in initial_state.items()}

    for _ in range(horizon):
        # The actor loss below is REINFORCE-style and only uses log-probs.
        # Keep imagined dynamics detached so we do not backpropagate through
        # the world model or through earlier imagined actions.
        feat = rssm.state_features(state).detach()
        action, lp, ent = actor(feat, sample=True)

        feats.append(feat)
        actions.append(action.detach())
        log_probs.append(lp)
        entropies.append(ent)

        with torch.no_grad():
            # Predict reward and continue from current state
            reward_preds.append(rssm.decode_reward(feat).squeeze(-1))
            continue_preds.append(torch.sigmoid(rssm.decode_continue(feat).squeeze(-1)))

            # Step world model forward (no observation — use prior)
            h = rssm.sequence_step(state, action.detach())
            _, z = rssm.prior(h)
            state = {"h": h.detach(), "z": z.detach()}

    return {
        "feats": torch.stack(feats, dim=1),  # (B, H, feat_dim)
        "actions": torch.stack(actions, dim=1),  # (B, H, act_dim)
        "log_probs": torch.stack(log_probs, dim=1),  # (B, H)
        "entropies": torch.stack(entropies, dim=1),  # (B, H)
        "reward_preds": torch.stack(reward_preds, dim=1),  # (B, H)
        "continue_preds": torch.stack(continue_preds, dim=1),  # (B, H)
    }


def compute_lambda_returns(
    rewards: torch.Tensor,
    values: torch.Tensor,
    continues: torch.Tensor,
    gamma: float,
    lambda_: float,
) -> torch.Tensor:
    """Compute GAE-style lambda-returns.

    Parameters
    ----------
    rewards    : (B, H)  — predicted rewards (symexp decoded)
    values     : (B, H)  — value predictions (symexp decoded)
    continues  : (B, H)  — continue probabilities
    gamma, lambda_ : discount and trace-decay

    Returns
    -------
    returns : (B, H)
    """
    B, H = rewards.shape
    returns = torch.zeros_like(rewards)
    last = values[:, -1]

    for t in reversed(range(H)):
        if t == H - 1:
            next_val = last
        else:
            next_val = (1.0 - lambda_) * values[:, t + 1] + lambda_ * returns[:, t + 1]
        returns[:, t] = rewards[:, t] + gamma * continues[:, t] * next_val

    return returns


def train_actor_critic(
    rssm: RSSM,
    actor: Actor,
    critic: Critic,
    target_critic: Critic,
    actor_optimizer: torch.optim.Optimizer,
    critic_optimizer: torch.optim.Optimizer,
    initial_state: Dict[str, torch.Tensor],
    return_normalizer: ReturnNormalizer,
    horizon: int = 15,
    gamma: float = 0.997,
    lambda_: float = 0.95,
    entropy_coeff: float = 3e-4,
    slow_critic_decay: float = 0.98,
    parallel_module: nn.Module | None = None,
) -> Dict[str, float]:
    """One gradient step for actor and critic via imagination."""
    if parallel_module is None:
        traj = imagine_trajectory(rssm, actor, initial_state, horizon)

        feats = traj["feats"]
        feats_detached = feats.detach()
        rewards_sym = traj["reward_preds"]
        continues = traj["continue_preds"]
        log_probs = traj["log_probs"]
        entropies = traj["entropies"]

        rewards = symexp(rewards_sym.detach())

        with torch.no_grad():
            target_values_sym = target_critic(feats_detached).squeeze(-1)
            target_values = symexp(target_values_sym)
            lambda_returns = compute_lambda_returns(
                rewards, target_values, continues.detach(), gamma, lambda_
            )
            return_normalizer.update(lambda_returns)

        values_sym = critic(feats_detached).squeeze(-1)
        values_for_adv = symexp(target_critic(feats_detached).squeeze(-1))
    else:
        outputs = parallel_module(
            initial_state["h"],
            initial_state["z"],
            horizon,
            gamma,
            lambda_,
        )
        lambda_returns = outputs["lambda_returns"]
        values_sym = outputs["values_sym"]
        log_probs = outputs["log_probs"]
        entropies = outputs["entropies"]
        values_for_adv = outputs["values_for_adv"]
        return_normalizer.update(lambda_returns)

    critic_target = symlog(lambda_returns)
    critic_loss = F.mse_loss(values_sym, critic_target.detach())

    critic_optimizer.zero_grad(set_to_none=True)
    critic_loss.backward()
    nn.utils.clip_grad_norm_(critic.parameters(), 100.0)
    critic_optimizer.step()

    # --- Actor loss ---
    with torch.no_grad():
        advantages = lambda_returns - values_for_adv
        normed_advantages = return_normalizer.normalize(
            lambda_returns
        ) - return_normalizer.normalize(values_for_adv)

    # Reinforce + straight-through objective
    actor_loss = -(normed_advantages.detach() * log_probs).mean()
    entropy_loss = -entropy_coeff * entropies.mean()
    total_actor_loss = actor_loss + entropy_loss

    actor_optimizer.zero_grad(set_to_none=True)
    total_actor_loss.backward()
    nn.utils.clip_grad_norm_(actor.parameters(), 100.0)
    actor_optimizer.step()

    # --- Update slow critic (EMA) ---
    with torch.no_grad():
        for p, tp in zip(critic.parameters(), target_critic.parameters()):
            tp.data.mul_(slow_critic_decay).add_(p.data, alpha=1.0 - slow_critic_decay)

    return {
        "ac/actor_loss": float(actor_loss.item()),
        "ac/critic_loss": float(critic_loss.item()),
        "ac/entropy": float(entropies.mean().item()),
        "ac/return_mean": float(lambda_returns.mean().item()),
        "ac/advantage_mean": float(advantages.mean().item()),
    }


# ---------------------------------------------------------------------------
# DreamerV4PolicyAgent — inference wrapper
# ---------------------------------------------------------------------------


class DreamerV4PolicyAgent:
    """Drop-in replacement for the JAX DreamerV3 policy agent.

    Provides the same ``init_policy`` / ``policy`` interface expected by
    ``engine.trained_official_dreamerv3_controller``.
    """

    def __init__(
        self,
        rssm: RSSM,
        actor: Actor,
        *,
        device: torch.device | None = None,
    ):
        self.rssm = rssm
        self.actor = actor
        self.device = device or torch.device("cpu")
        self.rssm.to(self.device).eval()
        self.actor.to(self.device).eval()

    # ---- interface ----

    def init_policy(self, batch_size: int) -> Dict[str, np.ndarray]:
        """Return initial recurrent carry as numpy arrays."""
        state = self.rssm.initial_state(batch_size, self.device)
        return {k: v.detach().cpu().numpy() for k, v in state.items()}

    @torch.no_grad()
    def policy(
        self,
        carry: Dict[str, np.ndarray],
        obs: Dict[str, np.ndarray],
        mode: str = "eval",
    ) -> Tuple[Dict[str, np.ndarray], Dict[str, np.ndarray], Dict]:
        """Select action given observation and carry.

        Parameters
        ----------
        carry : dict of numpy arrays ("h", "z")
        obs   : dict  {"vector", "reward", "is_first", "is_last", "is_terminal"}
        mode  : "eval" or "explore"

        Returns
        -------
        (new_carry, acts, info)
        """
        # Reconstruct torch state
        h = torch.as_tensor(carry["h"], dtype=torch.float32, device=self.device)
        z = torch.as_tensor(carry["z"], dtype=torch.float32, device=self.device)

        vector = np.asarray(obs["vector"], dtype=np.float32)
        is_first = np.asarray(obs["is_first"]).reshape(-1).astype(bool)

        B = h.shape[0]

        # Reset state for batch elements where is_first is True
        for b in range(B):
            if is_first[b]:
                h[b] = 0.0
                z[b] = 0.0

        obs_t = torch.as_tensor(vector, dtype=torch.float32, device=self.device)
        if obs_t.ndim == 1:
            obs_t = obs_t.unsqueeze(0)

        prev_action = torch.zeros(B, self.actor.action_dim, device=self.device)

        state = {"h": h, "z": z}

        # Deterministic step
        new_h = self.rssm.sequence_step(state, prev_action)

        # Encode observation and get posterior
        embed = self.rssm.encode(obs_t)
        _, new_z = self.rssm.posterior(new_h, embed)

        new_state = {"h": new_h, "z": new_z}
        feat = self.rssm.state_features(new_state)

        # Select action
        if mode == "eval":
            action = self.actor.act_eval(feat)
        else:
            action, _, _ = self.actor(feat, sample=True)

        # Clip to [-1, 1]
        action_np = (
            action.detach()
            .cpu()
            .numpy()
            .clip(CONTINUOUS_ACTION_LOW, CONTINUOUS_ACTION_HIGH)
        )

        new_carry = {k: v.detach().cpu().numpy() for k, v in new_state.items()}
        acts = {"action": action_np}
        return new_carry, acts, {}


# ---------------------------------------------------------------------------
# Checkpoint save / load
# ---------------------------------------------------------------------------


def _write_latest_marker(checkpoint_file: Path) -> None:
    """Point the sibling ``latest`` marker at *checkpoint_file*."""
    latest_path = checkpoint_file.parent / "latest"
    try:
        if latest_path.is_symlink() or latest_path.exists():
            latest_path.unlink()
        latest_path.symlink_to(checkpoint_file.name)
    except OSError:
        latest_path.write_text(checkpoint_file.name, encoding="utf-8")


def _resolve_checkpoint_from_latest(ckpt_dir: Path) -> Path | None:
    latest_path = ckpt_dir / "latest"
    if not latest_path.exists():
        return None
    try:
        if latest_path.is_symlink():
            target = Path(os.readlink(str(latest_path)))
        else:
            target = Path(latest_path.read_text(encoding="utf-8").strip())
    except OSError:
        return None
    if not str(target):
        return None
    resolved = (ckpt_dir / target).resolve()
    if not resolved.exists():
        return None
    try:
        return Path(resolve_dreamerv4_checkpoint_artifact(resolved))
    except FileNotFoundError:
        return resolved if resolved.is_file() else None


def _find_checkpoint_file_in_directory(directory: Path) -> Path | None:
    for filename in DREAMERV4_CHECKPOINT_CANDIDATE_NAMES:
        direct = directory / filename
        if direct.is_file():
            return direct

    via_latest = _resolve_checkpoint_from_latest(directory)
    if via_latest is not None:
        return via_latest

    pt_files = sorted(
        [candidate for candidate in directory.iterdir() if candidate.is_file() and candidate.suffix == ".pt"],
        key=lambda candidate: candidate.stat().st_mtime,
        reverse=True,
    )
    if pt_files:
        return pt_files[0]

    nested_ckpt_dir = directory / "ckpt"
    if nested_ckpt_dir.is_dir():
        nested = _find_checkpoint_file_in_directory(nested_ckpt_dir)
        if nested is not None:
            return nested

    child_dirs = sorted(
        [candidate for candidate in directory.iterdir() if candidate.is_dir()],
        key=lambda candidate: candidate.stat().st_mtime,
        reverse=True,
    )
    for child_dir in child_dirs:
        for filename in DREAMERV4_CHECKPOINT_CANDIDATE_NAMES:
            nested = child_dir / filename
            if nested.is_file():
                return nested

        nested_pt_files = sorted(
            [candidate for candidate in child_dir.iterdir() if candidate.is_file() and candidate.suffix == ".pt"],
            key=lambda candidate: candidate.stat().st_mtime,
            reverse=True,
        )
        if nested_pt_files:
            return nested_pt_files[0]

    return None


def resolve_dreamerv4_checkpoint_artifact(path: str | os.PathLike[str]) -> str:
    """Resolve a DreamerV4 checkpoint file from a file or checkpoint directory."""
    candidate = Path(path).expanduser()
    if candidate.is_file():
        return str(candidate.resolve())

    if candidate.is_dir():
        resolved = _find_checkpoint_file_in_directory(candidate)
        if resolved is not None:
            return str(resolved.resolve())

        raise FileNotFoundError(
            "No DreamerV4 checkpoint artifact was found under "
            f"{candidate}. Expected one of {DREAMERV4_CHECKPOINT_CANDIDATE_NAMES!r} "
            "or another .pt file."
        )

    raise FileNotFoundError(f"DreamerV4 checkpoint path does not exist: {candidate}")


def publish_dreamerv4_checkpoint(
    checkpoint_path: str | os.PathLike[str],
    destination: str | os.PathLike[str],
) -> str:
    """Copy a trained checkpoint into a drop-in runtime location.

    Parameters
    ----------
    checkpoint_path:
        Path to a checkpoint file or checkpoint directory produced by the trainer.
    destination:
        Either a target directory (the file will be written as
        ``dreamerv4_agent.pt``) or an explicit ``.pt`` file path.
    """
    source_file = Path(resolve_dreamerv4_checkpoint_artifact(checkpoint_path))
    destination_path = Path(destination).expanduser()
    if destination_path.suffix == ".pt":
        target_file = destination_path
    else:
        target_file = destination_path / DEFAULT_DREAMERV4_CHECKPOINT_NAME

    target_file.parent.mkdir(parents=True, exist_ok=True)
    if source_file.resolve() != target_file.resolve():
        shutil.copy2(source_file, target_file)
    _write_latest_marker(target_file)
    return str(target_file.resolve())


def _save_checkpoint(
    path: str,
    rssm: RSSM,
    actor: Actor,
    critic: Critic,
    target_critic: Critic,
    step: int,
) -> None:
    """Save all model weights and config."""
    ckpt = {
        "world_model": rssm.state_dict(),
        "actor": actor.state_dict(),
        "critic": critic.state_dict(),
        "target_critic": target_critic.state_dict(),
        "config": {
            "obs_dim": rssm.obs_dim,
            "action_dim": rssm.action_dim,
            "hidden_size": rssm.hidden_size,
            "stoch_categories": rssm.stoch_categories,
            "stoch_classes": rssm.stoch_classes,
            "mlp_units": rssm.mlp_units,
        },
        "step": step,
    }
    os.makedirs(os.path.dirname(path), exist_ok=True)
    torch.save(ckpt, path)
    _write_latest_marker(Path(path))


def _build_models_from_config(
    config: Dict[str, Any],
    device: torch.device,
    *,
    compile_models: bool = False,
) -> Tuple[RSSM, Actor, Critic, Critic]:
    """Instantiate fresh models from a config dict.

    When *compile_models* is True the Actor and Critic networks are wrapped
    with ``torch.compile``.  The RSSM is **not** compiled because its
    ``observe()`` method contains a Python for-loop (GRU unrolling) that
    ``aot_eager`` cannot fuse — on MPS the compilation wrapper dispatch
    overhead actually makes the sequential loop *slower*.  The Actor and
    Critic are pure feedforward and benefit from compilation.
    """
    rssm = RSSM(
        obs_dim=config["obs_dim"],
        action_dim=config["action_dim"],
        hidden_size=config["hidden_size"],
        stoch_categories=config["stoch_categories"],
        stoch_classes=config["stoch_classes"],
        mlp_units=config["mlp_units"],
    ).to(device)

    state_feat_dim = (
        config["hidden_size"] + config["stoch_categories"] * config["stoch_classes"]
    )

    actor = Actor(
        state_feat_dim=state_feat_dim,
        action_dim=config["action_dim"],
        mlp_units=config["mlp_units"],
    ).to(device)

    critic = Critic(
        state_feat_dim=state_feat_dim,
        mlp_units=config["mlp_units"],
    ).to(device)

    target_critic = Critic(
        state_feat_dim=state_feat_dim,
        mlp_units=config["mlp_units"],
    ).to(device)
    # Initialise target critic to match critic
    target_critic.load_state_dict(critic.state_dict())

    if compile_models:
        # Only compile pure-feedforward networks.  The RSSM's sequential
        # GRU loop prevents meaningful kernel fusion on MPS/aot_eager and
        # the wrapper dispatch overhead hurts throughput.
        actor = _maybe_compile(actor, device)
        critic = _maybe_compile(critic, device)
        target_critic = _maybe_compile(target_critic, device)

    return rssm, actor, critic, target_critic


def load_dreamerv4_pytorch_agent(
    checkpoint_path: str,
    *,
    seed: int = 0,
    step_hours: float = 6.0,
) -> DreamerV4PolicyAgent:
    """Load a trained DreamerV4 agent from a ``.pt`` checkpoint.

    Parameters
    ----------
    checkpoint_path : path to the ``.pt`` file
    seed : random seed (sets torch manual seed)
    step_hours : simulation step size (stored for reference, not used in policy)

    Returns
    -------
    DreamerV4PolicyAgent ready for inference
    """
    torch.manual_seed(seed)
    device = _auto_detect_device()
    resolved_checkpoint = resolve_dreamerv4_checkpoint_artifact(checkpoint_path)

    ckpt = torch.load(resolved_checkpoint, map_location=device, weights_only=False)
    config = ckpt["config"]

    rssm, actor, _, _ = _build_models_from_config(config, device)

    rssm.load_state_dict(ckpt["world_model"])
    actor.load_state_dict(ckpt["actor"])

    rssm.eval()
    actor.eval()

    return DreamerV4PolicyAgent(rssm, actor, device=device)


# ---------------------------------------------------------------------------
# Training entry-point
# ---------------------------------------------------------------------------


def train_dreamerv4_native(args: argparse.Namespace) -> Dict[str, Any]:
    """Train a DreamerV4 agent on the blood supply simulation.

    ``args`` is expected to carry the fields documented in the module-level
    docstring (steps, seed, logdir, etc.).  Missing attributes fall back to
    sensible defaults.

    Metal GPU Optimisations
    -----------------------
    When the selected device is MPS (Apple Metal) the training loop applies
    the same class of acceleration techniques that the DreamerV3 JAX runner
    uses through ``jax-metal``:

    * **torch.compile (aot_eager)** — fuses Python dispatch overhead,
      analogous to JAX's XLA compilation cache.
    * **Async CPU ↔ GPU transfers** — ``non_blocking=True`` on tensor
      moves so the CPU can prepare the next batch while the GPU is busy.
    * **Reduced synchronisation** — ``optimizer.zero_grad(set_to_none=True)``
      avoids a GPU memset; ``.item()`` calls are batched to logging
      boundaries so intermediate gradient steps run without CPU stalls.
    * **MPS memory management** — ``PYTORCH_MPS_HIGH_WATERMARK_RATIO=0``
      lets the allocator grow/shrink dynamically (like JAX's
      ``XLA_PYTHON_CLIENT_PREALLOCATE=false``).
    * **MPS command-buffer flush** — ``torch.mps.synchronize()`` is called
      only at timing and checkpoint boundaries to avoid unnecessary stalls.
    Returns
    -------
    dict
        Runtime metadata including checkpoint and metrics paths. CLI callers
        can ignore the return value; notebook workflows use it directly.
    """
    # ---- lazy imports (avoid circular deps) ----
    from ppo_env import BloodSupplyEnv
    from ppo_shared import DREAMER_ACTION_DIM as ACTION_DIM
    from ppo_shared import OBS_DIM as OD
    from scenarios import SCENARIOS, TRAINING_SCENARIO_KEYS
    from train_mappo import load_training_context, prepare_mappo_scenario

    # ---- parse args with defaults ----
    steps: int = getattr(args, "steps", 50_000)
    seed: int = getattr(args, "seed", 0)
    logdir: str = getattr(args, "logdir", "dreamerv4_runs/default")
    step_hours: float = getattr(args, "step_hours", 6.0)
    scenario_str: str = getattr(args, "scenario", "train")
    batch_size: int = getattr(args, "batch_size", 16)
    requested_envs: int = int(getattr(args, "envs", 0))
    seq_len: int = getattr(args, "seq_len", 32)
    imagine_horizon: int = getattr(args, "imagine_horizon", 15)
    lr_world: float = getattr(args, "lr_world", 3e-4)
    lr_actor: float = getattr(args, "lr_actor", 1e-4)
    lr_critic: float = getattr(args, "lr_critic", 1e-4)
    save_every: int = getattr(args, "save_every", 5_000)
    log_every: int = getattr(args, "log_every", 100)
    prefill_steps: int = getattr(args, "prefill_steps", 1_000)
    train_ratio: float = max(0.0, float(getattr(args, "train_ratio", 1.0)))
    gamma: float = getattr(args, "gamma", 0.997)
    lambda_: float = getattr(args, "lambda_", 0.95)
    model_preset: str = str(getattr(args, "model_preset", "default"))
    hidden_size: int | None = getattr(args, "hidden_size", None)
    stoch_categories: int | None = getattr(args, "stoch_categories", None)
    stoch_classes: int | None = getattr(args, "stoch_classes", None)
    mlp_units: int | None = getattr(args, "mlp_units", None)
    device_str: str | None = getattr(args, "device", "auto")
    use_data_parallel: bool = bool(getattr(args, "use_data_parallel", True))
    max_cuda_devices: int = max(0, int(getattr(args, "max_cuda_devices", 0)))
    online_city_graph: bool = bool(getattr(args, "online_city_graph", False))

    # ---- reproducibility ----
    torch.manual_seed(seed)
    np.random.seed(seed)

    device = _resolve_device(device_str)
    cuda_device_ids = _resolve_cuda_device_ids(
        device,
        max_devices=max_cuda_devices,
    )
    data_parallel = _data_parallel_enabled(
        device,
        requested=use_data_parallel,
        batch_size=batch_size,
        device_ids=cuda_device_ids,
    )
    _configure_runtime_env(online_city_graph=online_city_graph)
    num_envs = _resolve_native_env_count(
        requested_envs,
        device=device,
        cuda_device_ids=cuda_device_ids,
    )

    # ---- Metal GPU detection (mirrors DreamerV3's choose_jax_runtime) ----
    _use_mps = device.type == "mps"
    _use_cuda = device.type == "cuda"
    _use_gpu = _use_mps or _use_cuda

    if _use_mps:
        print(
            "[DreamerV4] Apple Metal GPU detected — enabling MPS optimisations "
            "(torch.compile/aot_eager, async transfers, dynamic memory)",
            flush=True,
        )

    # ---- scenario handling ----
    if scenario_str == "train":
        scenario_keys = list(TRAINING_SCENARIO_KEYS)
    else:
        scenario_keys = [s.strip() for s in scenario_str.split(",")]

    scenario_templates = [prepare_mappo_scenario(SCENARIOS[k]) for k in scenario_keys]

    # ---- environment ----
    G, NORTH, SOUTH, EAST, WEST = load_training_context()

    envs = [
        BloodSupplyEnv(
            params=scenario_templates[0],
            G=G,
            north=NORTH,
            south=SOUTH,
            east=EAST,
            west=WEST,
            episode_hours=168.0,
            step_hours=step_hours,
            seed=seed + idx * 1000,
            scenario_templates=scenario_templates,
            action_mode="continuous",
        )
        for idx in range(num_envs)
    ]

    # ---- models (with optional torch.compile for GPU acceleration) ----
    config = _resolve_native_model_config(
        obs_dim=OD,
        action_dim=ACTION_DIM,
        preset=model_preset,
        hidden_size=hidden_size,
        stoch_categories=stoch_categories,
        stoch_classes=stoch_classes,
        mlp_units=mlp_units,
    )

    rssm, actor, critic, target_critic = _build_models_from_config(
        config,
        device,
        compile_models=_use_gpu and not data_parallel,
    )

    # ---- optimizers ----
    wm_optimizer = torch.optim.Adam(rssm.parameters(), lr=lr_world, eps=1e-5)
    actor_optimizer = torch.optim.Adam(actor.parameters(), lr=lr_actor, eps=1e-5)
    critic_optimizer = torch.optim.Adam(critic.parameters(), lr=lr_critic, eps=1e-5)
    world_model_parallel: nn.Module | None = None
    actor_critic_parallel: nn.Module | None = None
    if data_parallel:
        world_model_parallel = nn.DataParallel(
            _WorldModelLossModule(rssm),
            device_ids=cuda_device_ids,
            output_device=cuda_device_ids[0],
        )
        actor_critic_parallel = nn.DataParallel(
            _ActorCriticRolloutModule(rssm, actor, critic, target_critic),
            device_ids=cuda_device_ids,
            output_device=cuda_device_ids[0],
        )

    return_normalizer = ReturnNormalizer()
    replay = MultiEnvReplayBuffer(num_envs=num_envs, capacity=500_000)

    # ---- directories ----
    ckpt_dir = os.path.join(logdir, "ckpt")
    os.makedirs(ckpt_dir, exist_ok=True)
    metrics_path = os.path.join(logdir, "metrics.jsonl")

    # ---- metrics logging helper ----
    metric_buffer: List[Dict[str, Any]] = []

    def flush_metrics() -> None:
        if not metric_buffer:
            return
        with open(metrics_path, "a") as f:
            for m in metric_buffer:
                f.write(json.dumps(m) + "\n")
        metric_buffer.clear()

    def _reset_env(env_idx: int) -> np.ndarray:
        obs_raw = envs[env_idx].reset()
        if isinstance(obs_raw, tuple):
            obs_val, _ = obs_raw
        else:
            obs_val = obs_raw
        return np.asarray(obs_val, dtype=np.float32)

    # ---- MPS synchronisation helper ----
    def _mps_sync() -> None:
        """Flush the MPS command buffer so wall-clock timings are accurate.

        On non-MPS devices this is a no-op.  Equivalent to calling
        ``jax.block_until_ready`` in the DreamerV3 runner.
        """
        if _use_mps and hasattr(torch.mps, "synchronize"):
            torch.mps.synchronize()

    # ---- prefill ----
    print(
        f"[DreamerV4] Prefilling replay buffer with {prefill_steps} random steps ...",
        flush=True,
    )
    obs_vals = np.stack([_reset_env(env_idx) for env_idx in range(num_envs)], axis=0)
    is_first_flags = np.ones(num_envs, dtype=np.bool_)
    prefill_done = 0

    while prefill_done < prefill_steps:
        active_envs = min(num_envs, prefill_steps - prefill_done)
        actions = np.random.uniform(
            CONTINUOUS_ACTION_LOW,
            CONTINUOUS_ACTION_HIGH,
            size=(active_envs, ACTION_DIM),
        ).astype(np.float32)

        for env_idx in range(active_envs):
            action = actions[env_idx]
            step_result = envs[env_idx].step(action)
            if len(step_result) == 5:
                next_obs, reward, terminated, truncated, info = step_result
                done = terminated or truncated
            else:
                next_obs, reward, done, info = step_result

            replay.add(
                env_idx,
                obs_vals[env_idx],
                action,
                reward,
                bool(is_first_flags[env_idx]),
                done,
            )
            obs_vals[env_idx] = np.asarray(next_obs, dtype=np.float32)
            is_first_flags[env_idx] = False

            if done:
                obs_vals[env_idx] = _reset_env(env_idx)
                is_first_flags[env_idx] = True

        prefill_done += active_envs

    print(f"[DreamerV4] Replay buffer filled: {replay.size} transitions", flush=True)

    # ---- main training loop ----
    obs_vals = np.stack([_reset_env(env_idx) for env_idx in range(num_envs)], axis=0)
    is_first_flags = np.ones(num_envs, dtype=np.bool_)
    episode_rewards = np.zeros(num_envs, dtype=np.float32)
    episode_count = 0
    env_steps = 0
    grad_steps = 0
    _mps_sync()  # Flush any pending MPS work before starting the timer
    t_start = time.time()
    train_budget = 0.0
    policy_state = rssm.initial_state(num_envs, device)
    prev_action_t = torch.zeros(
        num_envs, ACTION_DIM, dtype=torch.float32, device=device
    )

    # Pre-allocate a reusable tensor for the first-step mask on the GPU so
    # we avoid a CPU→GPU transfer every collection step.  This mirrors the
    # JAX-style "donate buffer" pattern used by the DreamerV3 runner.
    _first_mask_buf = torch.zeros(num_envs, 1, dtype=torch.float32, device=device)

    # Accumulated metrics for logging
    wm_metrics_acc: Dict[str, list] = {}
    ac_metrics_acc: Dict[str, list] = {}

    print(f"[DreamerV4] Training for {steps} environment steps ...", flush=True)
    print(f"[DreamerV4]   device         = {device}")
    if _use_mps:
        print("[DreamerV4]   metal_gpu      = ENABLED (MPS + torch.compile/aot_eager)")
    elif _use_cuda:
        if data_parallel:
            print("[DreamerV4]   cuda_gpu       = ENABLED (multi-GPU data parallel)")
        else:
            print("[DreamerV4]   cuda_gpu       = ENABLED (torch.compile/inductor)")
    else:
        print("[DreamerV4]   accelerator    = none (CPU)")
    print(f"[DreamerV4]   logdir         = {logdir}")
    print(f"[DreamerV4]   scenarios      = {scenario_keys}")
    print(f"[DreamerV4]   envs           = {num_envs}")
    print(f"[DreamerV4]   model_preset   = {model_preset}")
    print(
        "[DreamerV4]   model_dims     = "
        f"h={config['hidden_size']} z={config['stoch_categories']}x{config['stoch_classes']} "
        f"mlp={config['mlp_units']}"
    )
    if data_parallel:
        print(
            f"[DreamerV4]   data_parallel  = ENABLED across CUDA devices {cuda_device_ids}",
            flush=True,
        )
    elif _use_cuda and len(cuda_device_ids) > 1 and use_data_parallel:
        print(
            "[DreamerV4]   data_parallel  = disabled because batch_size is smaller "
            "than the number of visible CUDA devices or a single CUDA device was selected.",
            flush=True,
        )
    print(f"[DreamerV4]   batch_size     = {batch_size}")
    print(f"[DreamerV4]   seq_len        = {seq_len}")
    print(f"[DreamerV4]   imagine_horizon= {imagine_horizon}")
    print(f"[DreamerV4]   train_ratio    = {train_ratio}", flush=True)
    print(
        "[DreamerV4]   simulator      = "
        f"{'online city graph' if online_city_graph else 'offline fast path'}",
        flush=True,
    )

    # Adaptive log schedule: log early so the user sees output quickly,
    # then settle into the regular ``log_every`` cadence.
    _early_log_steps = {1, 2, 5, 10, 25, 50}

    while env_steps < steps:
        prev_env_steps = env_steps
        active_envs = min(num_envs, steps - env_steps)

        # --- collect one environment step ---
        rssm.eval()
        actor.eval()

        with torch.no_grad():
            if active_envs < 1:
                break

            # Build first-step mask on GPU — write into pre-allocated buffer
            # instead of creating a new CPU tensor and transferring it each
            # iteration (a significant MPS latency win).
            _first_mask_buf[:active_envs, 0] = torch.as_tensor(
                is_first_flags[:active_envs], dtype=torch.float32, device=device
            )
            first_mask = _first_mask_buf[:active_envs]

            policy_state["h"][:active_envs] *= 1.0 - first_mask
            policy_state["z"][:active_envs] *= 1.0 - first_mask
            prev_action_t[:active_envs] *= 1.0 - first_mask

            # Async CPU→GPU transfer for observation tensor.
            obs_t = torch.from_numpy(obs_vals[:active_envs]).to(
                device, non_blocking=True
            )

            active_state = {
                "h": policy_state["h"][:active_envs],
                "z": policy_state["z"][:active_envs],
            }
            h = rssm.sequence_step(active_state, prev_action_t[:active_envs])
            embed = rssm.encode(obs_t)
            _, z = rssm.posterior(h, embed)
            policy_state["h"][:active_envs] = h
            policy_state["z"][:active_envs] = z
            feat = rssm.state_features({"h": h, "z": z})
            action_t, _, _ = actor(feat, sample=True)
            prev_action_t[:active_envs] = action_t.detach()
            actions = (
                action_t.cpu()
                .numpy()
                .clip(CONTINUOUS_ACTION_LOW, CONTINUOUS_ACTION_HIGH)
            )

        for env_idx in range(active_envs):
            step_result = envs[env_idx].step(actions[env_idx])
            if len(step_result) == 5:
                next_obs, reward, terminated, truncated, info = step_result
                done = terminated or truncated
            else:
                next_obs, reward, done, info = step_result

            replay.add(
                env_idx,
                obs_vals[env_idx],
                actions[env_idx],
                reward,
                bool(is_first_flags[env_idx]),
                done,
            )
            episode_rewards[env_idx] += float(reward)
            env_steps += 1
            obs_vals[env_idx] = np.asarray(next_obs, dtype=np.float32)
            is_first_flags[env_idx] = False

            if done:
                episode_count += 1
                metric_buffer.append(
                    {
                        "step": env_steps,
                        "episode": episode_count,
                        "episode_reward": float(episode_rewards[env_idx]),
                        "time": time.time() - t_start,
                    }
                )
                episode_rewards[env_idx] = 0.0
                obs_vals[env_idx] = _reset_env(env_idx)
                is_first_flags[env_idx] = True

        # --- gradient steps ---
        if (
            replay.size < batch_size * seq_len
            or train_ratio <= 0.0
            or not replay.can_sample(seq_len)
        ):
            continue
        train_budget += train_ratio * active_envs
        n_train_steps = int(train_budget)
        train_budget -= n_train_steps
        if n_train_steps < 1:
            continue

        rssm.train()
        actor.train()
        critic.train()

        for _ in range(n_train_steps):
            batch = replay.sample(batch_size, seq_len)

            # Train world model — also returns the final posterior state
            # so we can seed imagination without a redundant observe() call.
            wm_info, init_state = train_world_model(
                rssm,
                wm_optimizer,
                batch,
                device,
                free_nats=1.0,
                kl_balance=0.8,
                parallel_module=world_model_parallel,
            )
            for k, v in wm_info.items():
                wm_metrics_acc.setdefault(k, []).append(v)

            # Train actor-critic via imagination
            ac_info = train_actor_critic(
                rssm,
                actor,
                critic,
                target_critic,
                actor_optimizer,
                critic_optimizer,
                init_state,
                return_normalizer,
                horizon=imagine_horizon,
                gamma=gamma,
                lambda_=lambda_,
                entropy_coeff=3e-4,
                slow_critic_decay=0.98,
                parallel_module=actor_critic_parallel,
            )
            for k, v in ac_info.items():
                ac_metrics_acc.setdefault(k, []).append(v)

            grad_steps += 1

        # --- logging ---
        crossed_early_log = any(
            prev_env_steps < s <= env_steps for s in _early_log_steps
        )
        crossed_regular_log = log_every > 0 and (
            prev_env_steps // log_every != env_steps // log_every
        )
        _should_log = crossed_early_log or crossed_regular_log
        if _should_log:
            # Synchronise MPS before reading wall-clock so the timing
            # reflects actual GPU work, not just CPU-side dispatch.
            _mps_sync()
            elapsed = time.time() - t_start
            fps = env_steps / max(elapsed, 1e-6)

            log_entry: Dict[str, Any] = {
                "step": env_steps,
                "grad_steps": grad_steps,
                "episodes": episode_count,
                "fps": round(fps, 1),
                "buffer_size": replay.size,
            }

            # Average accumulated world-model metrics
            for k, vals in wm_metrics_acc.items():
                log_entry[k] = round(float(np.mean(vals)), 5)
            wm_metrics_acc.clear()

            # Average accumulated actor-critic metrics
            for k, vals in ac_metrics_acc.items():
                log_entry[k] = round(float(np.mean(vals)), 5)
            ac_metrics_acc.clear()

            metric_buffer.append(log_entry)
            flush_metrics()

            # Console summary
            wm_total = log_entry.get("wm/total", 0.0)
            ac_actor = log_entry.get("ac/actor_loss", 0.0)
            ac_critic = log_entry.get("ac/critic_loss", 0.0)
            print(
                f"[DreamerV4] step {env_steps:>7d} | grad {grad_steps:>7d} | "
                f"ep {episode_count:>4d} | fps {fps:5.1f} | "
                f"wm {wm_total:.4f} | act {ac_actor:.4f} | crit {ac_critic:.4f}",
                flush=True,
            )

        # --- checkpointing ---
        crossed_save_boundary = save_every > 0 and (
            prev_env_steps // save_every != env_steps // save_every
        )
        if crossed_save_boundary:
            # Ensure all MPS kernels have completed before writing to disk.
            _mps_sync()
            ckpt_path = os.path.join(ckpt_dir, DEFAULT_DREAMERV4_CHECKPOINT_NAME)
            _save_checkpoint(ckpt_path, rssm, actor, critic, target_critic, env_steps)
            print(
                f"[DreamerV4] Checkpoint saved -> {ckpt_path}  (step {env_steps})",
                flush=True,
            )
            # Release any MPS cached allocations back to the system after a
            # checkpoint so long-running sessions stay within memory budget.
            if _use_mps and hasattr(torch.mps, "empty_cache"):
                torch.mps.empty_cache()

    # ---- final save ----
    _mps_sync()
    flush_metrics()
    ckpt_path = os.path.join(ckpt_dir, DEFAULT_DREAMERV4_CHECKPOINT_NAME)
    _save_checkpoint(ckpt_path, rssm, actor, critic, target_critic, env_steps)
    print(
        f"[DreamerV4] Training complete.  Final checkpoint -> {ckpt_path}", flush=True
    )
    print(f"[DreamerV4]   total env steps  = {env_steps}")
    print(f"[DreamerV4]   total grad steps = {grad_steps}")
    print(f"[DreamerV4]   total episodes   = {episode_count}")
    elapsed_final = time.time() - t_start
    print(f"[DreamerV4]   wall time        = {elapsed_final:.1f}s", flush=True)
    if env_steps > 0:
        print(
            f"[DreamerV4]   avg throughput   = {env_steps / max(elapsed_final, 1e-6):.1f} env-steps/s",
            flush=True,
        )
    if _use_mps and hasattr(torch.mps, "empty_cache"):
        torch.mps.empty_cache()

    for env in envs:
        env.close()

    return {
        "device": str(device),
        "checkpoint_path": str(Path(ckpt_path).resolve()),
        "metrics_path": str(Path(metrics_path).resolve()),
        "logdir": str(Path(logdir).resolve()),
        "env_steps": int(env_steps),
        "grad_steps": int(grad_steps),
        "episodes": int(episode_count),
        "train_ratio": float(train_ratio),
        "envs": int(num_envs),
        "cuda_device_ids": list(cuda_device_ids),
        "data_parallel": bool(data_parallel),
        "model_config": dict(config),
    }


# ---------------------------------------------------------------------------
# CLI entry-point
# ---------------------------------------------------------------------------


def _build_default_args() -> argparse.Namespace:
    """Return an argparse.Namespace with all default training hyper-parameters."""
    return argparse.Namespace(
        steps=50_000,
        seed=0,
        logdir="dreamerv4_runs/default",
        step_hours=6.0,
        scenario="train",
        envs=0,
        model_preset="default",
        hidden_size=None,
        stoch_categories=None,
        stoch_classes=None,
        mlp_units=None,
        batch_size=16,
        seq_len=32,
        imagine_horizon=15,
        lr_world=3e-4,
        lr_actor=1e-4,
        lr_critic=1e-4,
        save_every=5_000,
        log_every=100,
        prefill_steps=1_000,
        train_ratio=1.0,
        gamma=0.997,
        lambda_=0.95,
        online_city_graph=False,
        device="auto",
        use_data_parallel=True,
        max_cuda_devices=0,
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Train a native PyTorch DreamerV4 agent on the blood supply simulation.",
    )
    parser.add_argument("--steps", type=int, default=50_000)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--logdir", type=str, default="dreamerv4_runs/default")
    parser.add_argument("--step-hours", type=float, default=6.0, dest="step_hours")
    parser.add_argument("--scenario", type=str, default="train")
    parser.add_argument("--envs", type=int, default=0)
    parser.add_argument(
        "--model-preset",
        type=str,
        choices=sorted(NATIVE_MODEL_PRESETS),
        default="default",
        dest="model_preset",
    )
    parser.add_argument("--hidden-size", type=int, default=None, dest="hidden_size")
    parser.add_argument(
        "--stoch-categories", type=int, default=None, dest="stoch_categories"
    )
    parser.add_argument("--stoch-classes", type=int, default=None, dest="stoch_classes")
    parser.add_argument("--mlp-units", type=int, default=None, dest="mlp_units")
    parser.add_argument("--batch-size", type=int, default=16, dest="batch_size")
    parser.add_argument("--seq-len", type=int, default=32, dest="seq_len")
    parser.add_argument(
        "--imagine-horizon", type=int, default=15, dest="imagine_horizon"
    )
    parser.add_argument("--lr-world", type=float, default=3e-4, dest="lr_world")
    parser.add_argument("--lr-actor", type=float, default=1e-4, dest="lr_actor")
    parser.add_argument("--lr-critic", type=float, default=1e-4, dest="lr_critic")
    parser.add_argument("--save-every", type=int, default=5_000, dest="save_every")
    parser.add_argument("--log-every", type=int, default=100, dest="log_every")
    parser.add_argument(
        "--prefill-steps", type=int, default=1_000, dest="prefill_steps"
    )
    parser.add_argument("--train-ratio", type=float, default=1.0, dest="train_ratio")
    parser.add_argument("--gamma", type=float, default=0.997)
    parser.add_argument("--lambda", type=float, default=0.95, dest="lambda_")
    parser.add_argument(
        "--online-city-graph",
        action=argparse.BooleanOptionalAction,
        default=False,
        dest="online_city_graph",
        help="Use live city-graph loading instead of the offline fast path.",
    )
    parser.add_argument(
        "--device",
        type=str,
        default="auto",
        help=(
            "Device: 'auto' (detect GPU — prefers MPS on Apple Silicon, "
            "CUDA elsewhere), 'cpu', 'cuda', 'mps'.  When MPS is selected "
            "the trainer enables Metal GPU optimisations (torch.compile/"
            "aot_eager, async transfers, dynamic MPS memory) to match "
            "the DreamerV3 JAX-Metal training speed."
        ),
    )
    parser.add_argument(
        "--use-data-parallel",
        action=argparse.BooleanOptionalAction,
        default=True,
        dest="use_data_parallel",
        help=(
            "On CUDA, shard the optimization batches across all visible GPUs with "
            "torch.nn.DataParallel. Automatically disabled for single-GPU runs."
        ),
    )
    parser.add_argument(
        "--max-cuda-devices",
        type=int,
        default=0,
        dest="max_cuda_devices",
        help=(
            "Optional cap on the number of visible CUDA devices to use for data "
            "parallel training. 0 means use every visible CUDA device."
        ),
    )

    cli_args = parser.parse_args()
    train_dreamerv4_native(cli_args)
