# Generated by Django 5.2.13 on 2026-04-20 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('wilaya', models.CharField(blank=True, default='', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_id', models.CharField(max_length=20, unique=True)),
                ('event_timestamp', models.DateTimeField()),
                ('city_id', models.CharField(max_length=20)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('availability', models.IntegerField()),
                ('blood_group', models.CharField(max_length=5)),
                ('recency_days', models.IntegerField()),
                ('frequency_365', models.IntegerField()),
                ('days_until_eligible', models.IntegerField()),
                ('cluster_id', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['donor_id', 'event_timestamp'], name='inventory_d_donor_i_731740_idx')],
            },
        ),
        migrations.CreateModel(
            name='HospitalSupplyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.CharField(db_index=True, max_length=20)),
                ('event_timestamp', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('rain_mm', models.FloatField()),
                ('holiday', models.IntegerField()),
                ('disaster', models.IntegerField()),
                ('scheduled_surgeries', models.IntegerField()),
                ('trauma_cases', models.IntegerField()),
                ('current_inventory', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['hospital_id', 'event_timestamp'], name='inventory_h_hospita_45c078_idx')],
            },
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=50)),
                ('entity_type', models.CharField(max_length=30)),
                ('model_name', models.CharField(choices=[('stockout_lstm', 'Stockout LSTM'), ('hospital_shortage_predictor', 'Hospital Shortage XGBoost'), ('donor_propensity_model', 'Donor Propensity XGBoost')], max_length=50)),
                ('model_version', models.CharField(default='champion', max_length=20)),
                ('predicted_value', models.FloatField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('predicted_for_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert_triggered', models.BooleanField(default=False)),
                ('alert_threshold_used', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_id', 'model_name', 'predicted_for_date'], name='inventory_p_entity__95910d_idx')],
                'unique_together': {('entity_id', 'model_name', 'predicted_for_date')},
            },
        ),
        migrations.CreateModel(
            name='BloodSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_id', models.CharField(max_length=20, unique=True)),
                ('blood_product_type', models.CharField(max_length=5)),
                ('current_stock_units', models.FloatField()),
                ('usage_today', models.FloatField(default=0)),
                ('lead_time_days', models.IntegerField(default=3)),
                ('days_since_last_restock', models.IntegerField(default=0)),
                ('stockout_count_90d', models.IntegerField(default=0)),
                ('scheduled_surgeries_next7d', models.IntegerField(default=0)),
                ('event_timestamp', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='inventory.hospital')),
            ],
            options={
                'indexes': [models.Index(fields=['supply_id', 'event_timestamp'], name='inventory_b_supply__1aafda_idx')],
            },
        ),
    ]
