# Generated by Django 5.2.11 on 2026-04-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='donor',
            name='wilaya',
            field=models.CharField(default='', max_length=50),
        ),
    ]
