# Generated by Django 5.2.13 on 2026-04-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_donor_name_donor_wilaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionresult',
            name='blood_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='hospital_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='predictionresult',
            index=models.Index(fields=['hospital_id', 'blood_type', 'predicted_for_date'], name='inventory_p_hospita_c1e77a_idx'),
        ),
    ]
