# Generated by Django 5.2.13 on 2026-05-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_predictionresult_blood_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionresult',
            name='model_name',
            field=models.CharField(choices=[('stockout_days_predictor', 'Stockout LSTM'), ('hospital_shortage_predictor', 'Hospital Shortage XGBoost'), ('donor_propensity_model', 'Donor Propensity XGBoost')], max_length=50),
        ),
    ]
