# Generated by Django 5.2.13 on 2026-05-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_predictionresult_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionresult',
            name='model_name',
            field=models.CharField(max_length=128),
        ),
    ]
