# Generated by Django 5.2.13 on 2026-05-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_predictionresult_config_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalsupplyfeature',
            name='current_inventory',
            field=models.FloatField(),
        ),
    ]
