# Generated by Django 5.2.11 on 2026-05-04 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_fix_current_inventory_float'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodSupplySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_product_type', models.CharField(max_length=10)),
                ('current_stock_units', models.FloatField()),
                ('usage_today', models.FloatField()),
                ('days_since_last_restock', models.IntegerField()),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='inventory.hospital')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['hospital', 'blood_product_type', 'recorded_at'], name='inventory_b_hospita_3627c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_product_type', models.CharField(max_length=10)),
                ('forecast_date', models.DateField()),
                ('horizon', models.CharField(max_length=5)),
                ('predicted_units', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='inventory.hospital')),
            ],
            options={
                'indexes': [models.Index(fields=['hospital', 'blood_product_type', 'horizon'], name='inventory_s_hospita_071412_idx'), models.Index(fields=['hospital', 'blood_product_type', 'forecast_date'], name='inventory_s_hospita_6e1529_idx')],
                'unique_together': {('hospital', 'blood_product_type', 'forecast_date', 'horizon')},
            },
        ),
    ]
